### ISSUE TITLE
file absolute path

### ISSUE THREAD

**Issue by NayakBoy** [miguelpruivo/flutter_file_picker#1032]
please add a feature that we can get the absolute path of the file who's I selected. and select files not stored in the temp folder.

**Comment by miguelpruivo** [comment]
@NayakBoy this has been explained multiple times and it's even on the wiki, but once again, this is no longer possible since SDK 30 (Android) and on iOS it has never been possible. To work with the absolute files (this is, not copies) you'll have to manage through persistent file access (URI on Android and secure bookmarks on iOS).

This is only possible in the native way, since you can't open Dart `File` instances pointing to those objects, it always require an absolute path which is only reliable and possible, as of now, through copy (aka caching).

That's just a Flutter/Dart limitation, I'm sorry.

**Comment by xuqiqiang** [comment]
You can consider this library:
[https://pub.dev/packages/file_picker_fork](https://pub.dev/packages/file_picker_fork)
