### ISSUE TITLE
Gives error in SDWebimage at ios side when try to run app!!

### ISSUE THREAD

**Issue by coderGirl9796** [miguelpruivo/flutter_file_picker#1064]
ARC Semantic Issue (Xcode): No visible @interface for 'UIImage' declares the selector 'imageByPreparingForDisplay'
project_path/ios/Pods/SDWebImage/SDWebImage/Core/SDImageCoderHelper.m:373:39

**Comment by JavierMalebran** [comment]
i have the same problem any solution

**Comment by AraxTheCoder** [comment]
I have the same problem.
According to my research, the problem occurred around the same time as the SDWebimage library had a new release .

> "Support using iOS 15 UIImage new API imageByPreparingForDisplay for faster force decoding #3355 #3340".

Unfortunately, I don't know enough about iOS development.
Can anyone help me with this?

**Comment by AraxTheCoder** [comment]
@JavierMalebran @coderGirl9796 
I think I have found the problem.
I personally worked with Xcode 12.2.
This version supports only iOS SDK 14.2 according to https://xcodereleases.com.
The bug comes from a method introduced in the iOS 15 SDK and therefore not yet available (https://developer.apple.com/documentation/uikit/uiimage/3750834-imagebypreparingfordisplay).

The "solution" to the problem is either to upgrade macOS and install a newer version of Xcode or to use the SDWebImage library before updating.

The latter can be done with:
`pod 'SDWebImage', '5.12.6'`
in the pod file.

Inserted it looks like this:
```
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  pod 'SDWebImage', '5.12.6'
end
```

This won't get any new updates of the library though, so you should try to get a new Xcode version running.
