### ISSUE TITLE
FilePicker is picking all files from gallery but i have allowed only pdf extension 

### ISSUE THREAD

**Issue by ChiggosTeam** [miguelpruivo/flutter_file_picker#1075]
version -  file_picker: ^4.6.1

**Describe the bug**
FilePicker is picking all files from gallery but i have allowed only pdf extension 

**Platform**
 - Android

**Platform OS version**
Android 9

 final file = await filepicker.FilePicker.platform.pickFiles(
        type: filepicker.FileType.custom,
        allowedExtensions: [
          'pdf',
        ],
        withData: true);

**Comment by Abdelazeem777** [comment]
Same Here! 🥲

**Comment by minhnguyenandpad** [comment]
Why no one fix this :((

**Comment by expertdev-designer** [comment]
@miguelpruivo i also have same issue

**Comment by miguelpruivo** [comment]
Maybe the picker that you're launching isn't respecting the constraints. This could be an issue on Android devices, since it lets the user use the picker he wants.

You should double check on your end if the files are valid. This is [the first question](https://github.com/miguelpruivo/flutter_file_picker/wiki/FAQ) in the FAQ.

**Comment by KishanViramgama** [comment]
Hiii @miguelpruivo I am facing same issue do you have find any solution or not. Do you have any further updates or not about this bug.

**Comment by hadiabdulla** [comment]
any update on this bug
