### ISSUE TITLE
file_picker ^5.0.1 is not compatible with connectivity_plus ^2.3.6+1

### ISSUE THREAD

**Issue by luiscarielo83** [miguelpruivo/flutter_file_picker#1097]
**Describe the bug**
Because dbus >=0.7.4 depends on xml ^6.1.0 and dbus >=0.5.5 <0.7.5 depends on ffi ^1.1.2, dbus >=0.5.5 requires xml ^6.1.0 or ffi ^1.1.2.
And because file_picker >=5.0.0 depends on ffi ^2.0.1 and nm 0.5.0 depends on dbus ^0.7.0, if file_picker >=5.0.0 and nm 0.5.0 then xml ^6.1.0.
And because no versions of nm match >0.5.0 <0.6.0 and connectivity_plus_linux >=1.3.0 depends on nm ^0.5.0, if file_picker >=5.0.0 and connectivity_plus_linux >=1.3.0 then xml ^6.1.0.
And because connectivity_plus 2.3.6+1 depends on connectivity_plus_linux ^1.3.0 and no versions of connectivity_plus match >2.3.6+1 <3.0.0, if file_picker >=5.0.0 and connectivity_plus ^2.3.6+1 then xml ^6.1.0.
And because cexpira_movil depends on excel from git which depends on xml ^5.0.2, file_picker >=5.0.0 is incompatible with connectivity_plus ^2.3.6+1.
So, because cexpira_movil depends on both connectivity_plus ^2.3.6+1 and file_picker ^5.0.1, version solving failed.

**Platform**

- [ * ] Android
- [ * ] iOS
- [ ] Web
- [ ] Desktop

**Flutter Version details**
` Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-x64, locale es-419)
    • Flutter version 3.0.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2
`

**Comment by lordscales91** [comment]
Damn! That's some good old dependency hell right there. I come from a Java background and those are very common there. I'm still a newbie in the Dart land, but maybe it's possible to force certain dependency versions or exclude certain dependencies. That's how we usually solve it there, not sure if it's possible with Dart though. 

I don't there's anything that this plugin alone can change to fix your particular issue (again, I could be wrong because I'm still don't know much about the Dart and Flutter ecosystem). I'm afraid this is something you will have to figure out on your own. I wish you the best of luck.
