### ISSUE TITLE
For windows please support read tag from file

### ISSUE THREAD

**Issue by radheyshyamjat** [miguelpruivo/flutter_file_picker#1240]
Read documentation but not found any method to read tag of file. Anything planning for this.

**Comment by philenius** [comment]
Could you please elaborate on `read tag of file`? I'm not familiar with the concept of file tags.

**Comment by radheyshyamjat** [comment]
https://zapier.com/blog/how-to-use-tags-and-labels/
Please check this link you may get few information about tags of file

**Comment by philenius** [comment]
@radheyshyamjat alright, I did some research for you. The blog post that you referenced covers the usage of _tags_ in different applications or on different operating systems. However, this is not the correct technical term. What you actually want is to extract the so-called _extended file attributes_ (see [Wikipedia](https://en.m.wikipedia.org/wiki/Extended_file_attributes)).
In Python, there's a dedicated package to extract this information from a file ([see this StackOverflow post](https://stackoverflow.com/questions/33181948/how-to-get-extended-macos-attributes-of-a-file-using-python)). However, I couldn't find a similar Dart package.

I will close this issue because this Dart package, _file_picker_, is not responsible for reading the actual file. This package only returns the **path** to the file(s) that the user picked. From there on, it is your responsibility to then read the file and extract the extended file attributes. Good luck!
