### ISSUE TITLE
set dialog language

### ISSUE THREAD

**Issue by mrudigier** [miguelpruivo/flutter_file_picker#1242]
Hi,

I am using the file_picker on macos (Monterey 12.5) with the system language/locale set to german.
Im using the following code to chose an image file:
```
FilePickerResult? result = await FilePicker.platform.pickFiles(
      allowMultiple: false,
      lockParentWindow: true,
      type: FileType.custom,
      allowedExtensions: AllowedAttachmentFileTypes.allowedFileExtension(),
    );
```
When the file picker window opens, the language of the dialog is a mix of german and english, e.g. it says "Cancel" on the cancel button, but "Auswählen" on the confirmation button.

I don't see a direct way to set the language for the file picker. Is it possible to allow this?

**Comment by philenius** [comment]
Hi @mrudigier, unfortunately, _file_picker_ for macOS is based on an approach with limited options. It works by executing a shell command named `osascript`, which can execute AppleScript commands. For picking files, we simply execute:

```bash
osascript -e "choose file"
```

Here you can find the [man pages of `osascript`](https://ss64.com/osx/osascript.html). From [Apple's documentation](https://developer.apple.com/library/archive/documentation/AppleScript/Conceptual/AppleScriptLangGuide/reference/ASLR_cmds.html#//apple_ref/doc/uid/TP40000983-CH216-SW4) it looks like the `choose file` command has no option to configure the language. Therefore, _file_picker_ does not offer this option. If you can find a way to change the language/text of the buttons through `osascript`, then let us know.

You could also try the official Flutter plugin named `file_selector` (https://pub.dev/packages/file_selector) with a native approach instead of executing shell commands.

**Comment by mrudigier** [comment]
Hi @philenius, thank you very much for your reply. I will check out the file_selector package.
