### ISSUE TITLE
How to pick file on android 13 as READ_EXTERNAL_STORAGE is not allowed.

### ISSUE THREAD

**Issue by surajpunemaha** [miguelpruivo/flutter_file_picker#1250]
**Describe the bug**
Platform exception: PlatformException(read_external_storage_denied, User did not allowed reading external storage, null, null)

**Platform**
Android 13

**How are you picking?**
```
FilePicker.platform.pickFiles(
   type: FileType.custom,
   allowedExtensions: ['pdf']
);
```

**Error Log**
```
[MethodChannelFilePicker] Platform exception: PlatformException(read_external_storage_denied, User did not allowed reading external storage, null, null)
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(read_external_storage_denied, User did not allowed reading external storage, null, null)
```

**Flutter Version details**
```
Flutter 3.7.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 62bd79521d (19 hours ago) • 2023-03-30 10:59:36 -0700
Engine • revision ec975089ac
Tools • Dart 2.19.6 • DevTools 2.20.1
```

**Comment by devkrutitech** [comment]
Add the following to your AndroidManifest.xml


<uses-permission android:name="com.google.android.gms.permission.AD_ID"/>
 <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"
 android:maxSdkVersion="33" />
 <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" 
   android:maxSdkVersion="33"  />
 <uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>
 <uses-permission android:name="android.permission.READ_MEDIA_VIDEO"/>
 <uses-permission android:name="android.permission.READ_MEDIA_AUDIO"/>


This basically specifies maxSdkVersion for read and write storage and you are good to go

**Comment by devkrutitech** [comment]
Add the following files to your android manifest this will help to provide max sdk version to which permission is granted and you are good to go

<uses-permission android:name="com.google.android.gms.permission.AD_ID"/>
 <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"
 android:maxSdkVersion="33" />
 <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" 
   android:maxSdkVersion="33"  />
 <uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>
 <uses-permission android:name="android.permission.READ_MEDIA_VIDEO"/>
 <uses-permission android:name="android.permission.READ_MEDIA_AUDIO"/>

**Comment by devkrutitech** [comment]
Add the following in your AndroidManifest.xml and you are good to go
[Solution.docx](https://github.com/miguelpruivo/flutter_file_picker/files/11131252/Solution.docx)

**Comment by DinoLing28** [comment]
The answer above only allow users to access to the media library to upload their videos, audio, and images with following permission :
 <uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>
 <uses-permission android:name="android.permission.READ_MEDIA_VIDEO"/>
 <uses-permission android:name="android.permission.READ_MEDIA_AUDIO"/>

<uses-permission android:name="com.google.android.gms.permission.AD_ID"/>
//this is to allow the app to access the advertising ID of the device.

 <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"
 android:maxSdkVersion="33" />
 <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" 
   android:maxSdkVersion="33"  />
//these 2 permission are used to allow device that below sdk 33 (Android 13) still available to work with asking permission on storage but not for this issue.

This issue was about the access denied to the storage of Android 13, and this causes an error on this library's pickFiles function. 
With research on many platforms, but all having the same answer - do not allow android 13 if you want to use pickFiles. 

I am not a pro but these are the results of my research, wish if any better solution could be provided. It also affecting my application since it requires users to upload documents.

**Comment by tuntorius** [comment]
In API level 33+, the storage permission must not be requested, because it doesn't exist. It seems the plugin handles that properly. Do you request that permission in your code as well? If so, don't. Directly proceed with file picking.
In fact, this permission is not needed in any Android version, if only the file picker is used. The picker itself is a permission request for the specific file. When the user picks it, permission is granted.

**Comment by surajpunemaha** [comment]
@devkrutitech, @DinoLing28 and @tuntorius thank you for your reply.
--------------------------
 @devkrutitech 
 I tried suggestion mentioned by you, but still getting same error. I also commented runtime request part (as mentioned by @tuntorius ) for android 13  but nothing seems to be worked.
 
 I think `READ_MEDIA_IMAGES` `READ_MEDIA_VIDEO` and `READ_MEDIA_AUDIO` might help when requested to pick Image, Video or Audio files respectively. But when it comes to picking .pdf or .docx files, these permissions are helpless.
 
I think, Now I need to think of different approach to pick files.

**Comment by surajpunemaha** [comment]
Whoooa. @tuntorius 
I was not on the latest version of library because of other library in my code is depending on `file_picker`.

Just to give try I commented the dependency part from code and used the latest version of  `file_picker` library and it **worked**.

Thanks for your help.

**Comment by PrasadDhend** [comment]
### **_Adding the below lines of code worked for me!_**

**android/app/build.gradle**

`compileSdkVersion 33`
`ndkVersion flutter.ndkVersion`


**android/app/src/main/AndroidManifest.xml**

`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>`
`<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>`
`<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE"/>`

### Take a permission using below code

`final status = await Permission.manageExternalStorage.request();`
`     if (status.isDenied ||`
`        status.isPermanentlyDenied ||`
`       status.isRestricted) {`
`    throw "Please allow storage permission to upload files";`
` }`

**Comment by tuntorius** [comment]
@surajpunemaha why do you use that other package at all? Just use file_picker directly. It makes a copy of the picked file into the **files** directory of your app, where you can read it using the dart io library. It's true that since the introduction of Scoped Storage in Android 10/11, the dart io library can't read files from the external storage anymore, but it can from your app's **files** directory. That is the reason why file_picker makes a copy of the file you picked, so you can read it directly in dart, without using a native code method.

**Comment by surajpunemaha** [comment]
@tuntorius I got it and resolved the other issue. Thanks for your time and help.
Going to close this thread.

Happy coding. Cheeersss.

**Comment by PaulTreu** [comment]
This is working in v51.

**Comment by juarezfranco** [comment]
MANAGE_EXTERNAL_STORAGE is a sensitive permission and my app is not accepted on the playstore because its purpose does not fit.

**Comment by Arthurlss** [comment]
hey guys, I have same issue, but I tried something and for me it worked.
I put all this permissions and before calling picke_file I ask to permission Permission.storage.request(). When I put this, worked!

This problem occourend only in Android 13, I guess

**Comment by abhisheksr227** [comment]
How this issue resolved?
