### ISSUE TITLE
Not working on Linux-Kylin

### ISSUE THREAD

**Issue by cuishijie1991** [miguelpruivo/flutter_file_picker#1282]
hi, When I run my app on Linux-Kylin, the file picker not working with exception :
_"flutter: Exception: Couldn't find the executable zenity in the path"_

I know that the Linux-Kylin is not a version of the operating system supported by the mainstream. But I still hope to get some help message to know how to fix it, thank u!

----------------
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[✓] Flutter (Channel stable, 3.10.0, on Kylin V10 SP1 5.10.0-8-generic, locale zh_CN.UTF-8)
    • Flutter version 3.10.0 on channel stable at /home/IT/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (8 天前), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4kylin1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1
[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
[✓] VS Code (version 1.78.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.64.0
[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Kylin V10 SP1 5.10.0-8-generic
[✓] Network resources
    • All expected network resources are available.

**Comment by philenius** [comment]
hi @cuishijie1991, thanks for your detailed description. Your issue is related to these ones: https://github.com/miguelpruivo/flutter_file_picker/issues/1270, https://github.com/miguelpruivo/flutter_file_picker/issues/1154, https://github.com/miguelpruivo/flutter_file_picker/issues/931, https://github.com/miguelpruivo/flutter_file_picker/issues/903

Unfortunately, `file_picker` won't work if neither `zenity`, nor `qarma`, nor `kdialog` are available and we don't have the skill-set to fix this issue. Maybe, you could try another Dart plugin named `file_selector` (https://pub.dev/packages/file_selector). This plugin provides a C++ implementation for Linux which should work on all Linux distributions.
