### ISSUE TITLE
Cannot resolve dependencies in 5.3.2 (5.3.1 works fine)

### ISSUE THREAD

**Issue by hicnar** [miguelpruivo/flutter_file_picker#1294]
![Screenshot 2023-05-25 at 13 51 21](https://github.com/miguelpruivo/flutter_file_picker/assets/1816194/3aed0a39-3ccd-492e-9c72-05c10ee6a14e)

**Comment by philenius** [comment]
Hi @hicnar , the output of `dart pub` is always a little confusing. But, here's the reason:
Seems like you are using a Dart package named `path_provider_windows`. This package depends on an older version of `win32`. [As you can see here](https://github.com/flutter/packages/blob/main/packages/path_provider/path_provider_windows/pubspec.yaml#L24), it depends on `win32: ">=2.1.0 <5.0.0"`.

`file_picker` depends on `win32`, too. But, some folks requested an update to the latest major v5 of `win32` (https://github.com/miguelpruivo/flutter_file_picker/issues/1280). This is why we bumped our `win32` dependency to `win32: '^5.0.2'` in https://github.com/miguelpruivo/flutter_file_picker/pull/1281 and released it with `file_picker` v5.3.2. However, switching from v4 to v5 of `win32` came with breaking changes so that we could not use a lose version constraint such as `win32: '>=3.0.0 <6.0.0'`.

Here are your options:
* Continue using v5.3.1 of `file_picker`, e.g by specifying in your `pubspec.yaml`:
   ```yaml
   file_picker: '>=5.3.0 <5.3.2'
   ```
* Write an issue in this repo https://github.com/flutter/packages/tree/main/packages/path_provider/path_provider_windows so that they update their win32 dependency to 5.x.y, too.

Please let me know, if you know a better approach to handle the recurring win32 dependency upgrades (this issue, previously https://github.com/miguelpruivo/flutter_file_picker/pull/1281, and before that https://github.com/miguelpruivo/flutter_file_picker/pull/1266).

**Comment by hicnar** [comment]
Thank you for your response. Just to clarify I do use path_provider butI build exclusively for iOS and Android so no Win dependencies should be in use. For now I indeed fixed the file_picker to 5.3.1 but following your advice I will open an issue with the path_provider folks. Thanks again!
