### ISSUE TITLE
File picker also picking file other than allowed extension

### ISSUE THREAD

**Issue by ck-lamib** [miguelpruivo/flutter_file_picker#1338]
File picker in android is picking .png, .jpg using the photo option from menu option even if the allowed extension is set to ['pdf'].

**Comment by miguelpruivo** [comment]
Hi, I assume this is on some Android device — some rom's doesn't respect the URI rules passed in the intent, specially if they use custom file explorers (which on its own, can do whatever they want to) so you should always double check on your app after picking. Assume the filter just a first triage on the devices that it actually works. On iOS though, should work on all since all use the same explorer.
