### ISSUE TITLE
Original filename renamed after being cached

### ISSUE THREAD

**Issue by agavrel** [miguelpruivo/flutter_file_picker#1395]
NB: Probably "as intended", not necessarily a bug. Please let me know.

**Describe the bug**
When picking a file, the file is cached and its name is then changed. I would like to keep the original filename, or have a way to keep/know the original filename right after selecting the file(s). Please advise.

**Platform**

- [ ] Android + Ios

**Platform OS version**
Latest

**How are you picking?**
```
With the latest example
```

**Details to reproduce the issue**
Pick one file.

**Comment by miguelpruivo** [comment]
That's intended, whenever the original file name can't be retrieved.

**Comment by tang5011235** [comment]
![图片](https://github.com/user-attachments/assets/740b30fd-e135-4b0f-89d3-75b2c394df71)
the problem is here ,you can set the paramter compressionQuality = 0 to avoid cache, but your image can not be compress.
![图片](https://github.com/user-attachments/assets/9faa0680-5b69-4820-99eb-7e04c9501a23)

@agavrel
