### ISSUE TITLE
App Crashes Frequently While Choosing Images or Videos

### ISSUE THREAD

**Issue by SelvaGanapthy** [miguelpruivo/flutter_file_picker#1402]
Hi, While Selecting the Custom Files the app Frequently crashes.  I think the exception was not handled and it is caused the internal library files. For your refers **file_picker: ^6.1.1**

**Platform**
-  Android Samsung Galaxy S8.

**Platform OS version**
 Android 9 Pie

**Details to reproduce the issue**
To reproduce the problem for that I gave sample coding for attachment.

**Error Log**
D/AndroidRuntime(30237): Shutting down VM
E/AndroidRuntime(30237): FATAL EXCEPTION: main
E/AndroidRuntime(30237): Process: com.agilysys.commonapp, PID: 30237
E/AndroidRuntime(30237): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(30237): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:435)
E/AndroidRuntime(30237): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:272)
E/AndroidRuntime(30237): 	at com.mr.flutter.plugin.filepicker.FilePickerPlugin$MethodResultWrapper$1.run(FilePickerPlugin.java:214)
E/AndroidRuntime(30237): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(30237): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(30237): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(30237): 	at android.ap
<img width="960" alt="app crash while large file selected" src="https://github.com/miguelpruivo/flutter_file_picker/assets/25679776/5eaa0a8a-cb03-4818-930c-88bfcdc25d03">
p.ActivityThread.main(ActivityThread.java:7073)
E/AndroidRuntime(30237): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30237): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/AndroidRuntime(30237): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
[log] Size Exceeded
I/Process (30237): Sending signal. PID: 30237 SIG: 9
Lost connection to Device.

**Screenshots **
 Added screens

**Flutter Version details**
Flutter version 3.16.0-20.0.pre.7

**Additional context**

**Comment by stilus-tayyipguzel** [comment]
I also get similar errors in file picker on some special devices. There is no problem in simulator tests. I catch these errors in crashlytics.

I added a stacktrace below. I noticed a situation like this: the issue is repeated multiple times within seconds. The crash was repeated 28 times until the file picker was opened, the image was selected and closed.

[stacktrace.txt](https://github.com/miguelpruivo/flutter_file_picker/files/13305602/stacktrace.txt)

## Devices: 
Galaxy A24 - Android 13
Galaxy A12 - Android 12
Infinix Note 30 - Android 13
Galaxy A04s - Android 13
Galaxy A72 - Android 13
Galaxy A73 5G - Android 13
Shine Lite - Android 6
Galaxy S10e - Android 12
MI6 - Android 9
A5 2020 - Android 10

## Version
file_picker: 5.3.3
flutter: 3.13.5

**Comment by sayedmoataz** [comment]
same error

**Comment by iampawan** [comment]
Facing similar issue
