### ISSUE TITLE
Current desktop support

### ISSUE THREAD

**Issue by jesusrp98** [miguelpruivo/flutter_file_picker#142]
I saw that this plugin currently supports desktop via `go-flutter`.

My question is, does that mean that the package doesn't support the `flutter-desktop-embedded` implementation?

**Comment by miguelpruivo** [comment]
That's correct @jesusrp98. Go Flutter is an alternative to Flutter Desktop that also provides a seamless desktop experience while making it easier to use native calls (because of the Go abstraction) for plugins such as this one.

**Comment by jesusrp98** [comment]
The thing is, `flutter-desktop-embedded` has been integrated into the main Flutter repo.

Wouldn't be better if the plugin would work with the 'official' desktop implementation in Flutter? How hard would it be?
Look [here](https://github.com/flutter/flutter/wiki/Desktop-shells) if you want to take a deeper look at it.

**Comment by miguelpruivo** [comment]
@jesusrp98 yes, I'm aware of that, the thing is that you need to add support for each single platform (Mac/Windows/Linux) native platform calls for this to work, it's not an easy task and you'll need to run and develop under the 3 platforms. Go-Flutter just uses the Flutter engine and makes this kind of tasks easier. 

You can check more details about it [here](https://github.com/go-flutter-desktop/go-flutter). However, I'm not discarding at all the possibility to add Desktop support sometime in the future, but definitely, and because we have the Go-Flutter Desktop implementation, is not on top of my priorities.

Anyhow, feel always free to issue a PR if you are up to it. 😃
