### ISSUE TITLE
FilePicker returns a cached filepath for images instead of the actual filepath

### ISSUE THREAD

**Issue by whigger85** [miguelpruivo/flutter_file_picker#150]
When I call the FilePicker.getFile() method with the defaults for type and extension, and I select an image in the dialog, than the returned filepath won't be the actual path of the image (e. g. the downloads directory), but a path to the temporarily cached image ('/data/user/0/<app_directory>/cache/image.jpg'). This is bad, because this cached version is deleted by the system automatically after a short period. Thus, working with this filepath is no longer possible afterwards.

Noticed this behaviour on Android. Not sure about iOS.

**Comment by miguelpruivo** [comment]
That happens when the file is probably remote (which happens a lot of times in the downloads folder as Android keeps only a reference for the remote file). The file is temporary cached because it is up to the developer to decide where it should be placed, so you should either move it or copy it to somewhere else, if you want to make it as a persistent file.

**Comment by whigger85** [comment]
Thanks for the quick response. I never heard of the case that android can simply store a reference to the remote file in the downloads folder. This is interesting. Do you have some Internet links for this topic?

Besides, I wanted to explicitly mention that the described problem only occurs with images. If I select a pdf file from the downloads folder, the correct file path is returned by the file picker.

**Comment by miguelpruivo** [comment]
Sorry for the late response @whigger85, I've been quite busy lately. I misunderstand the Downloads folder with the Recent files folder (in which, usually is just a reference for some file, like I said). In the downloads folder, typically that behavior will happen when the Content Resolver can't handle the file path and so you need to open an input stream and cache it yourself so it can be actually retrieved. This acts as a fallback attempt because the path could not be retrieved otherwise.

You can check the most upvoted answer about this [here](https://stackoverflow.com/questions/30671548/unknown-url-content-downloads-my-downloads).

**Comment by miguelpruivo** [comment]
Sorry for the late response @whigger85, I've been quite busy lately. I misunderstand the Downloads folder with the Recent files folder (in which, usually is just a reference for some file, like I said). In the downloads folder, typically that behavior will happen when the Content Resolver can't handle the file path and so you need to open an input stream and cache it yourself so it can be actually retrieved. This acts as a fallback attempt because the path could not be retrieved otherwise.

You can check the most upvoted answer about this [here](https://stackoverflow.com/questions/30671548/unknown-url-content-downloads-my-downloads).

I'm closing this for now as it might not represent actually an issue, but feel free to continue the discussion here.
