### ISSUE TITLE
multiple file picker in iOS not working properly

### ISSUE THREAD

**Issue by zmhbh** [miguelpruivo/flutter_file_picker#151]
![IMG_7765](https://user-images.githubusercontent.com/9757323/66179225-fe36fc80-e61c-11e9-961c-3cf1c4227225.PNG)
![IMG_7764](https://user-images.githubusercontent.com/9757323/66179229-02fbb080-e61d-11e9-8be2-d173c257c0d0.PNG)

**Comment by miguelpruivo** [comment]
Hi @zmhbh, I don’t see nothing wrong in the screenshots. Mind to explain? Thank you.

**Comment by zmhbh** [comment]
@miguelpruivo , I thought we should see the thumbnails of the images, just like the single-file scenario, also, when I click the image item, nothing happened.

**Comment by miguelpruivo** [comment]
@zmhbh no, just to let you know, that's up to the system to decide. As soon as you launch the picker, it's the OS side that's working on and there's nothing related to the plugin's implementation. That's probably because those pictures are missing the extension or something like that. Try with other photo files.

Since there's no issue at all related with `file_picker` I'm closing this.

Thank you.
