### ISSUE TITLE
File picker loses info when importing Android pictures (rotation + quality)

### ISSUE THREAD

**Issue by orevial** [miguelpruivo/flutter_file_picker#1518]
When I take a portrait picture on my **Android** phone and then use file picker plugin in my app to get this picture, the resulting picture (copied into a `file_picker` subdirectory) loses the original pictures information:

* The portrait picture has been rotated, I guess because the original picture EXIF metadata contained "Orientation : 90 CW"
* The copied picture has been compressed (a lot, like reduced by 90% or more)

Why is the info lost during the file copy ? Can't we have options to make deeper copies with EXIF metadata and proper compression ?
I read this [related issue](https://github.com/miguelpruivo/flutter_file_picker/issues/262) on image rotation which seems to say that it's due to the file explorer itself, however what I don't understand is that packages like [image_picker](https://pub.dev/packages/image_picker) manage to copy the image to a given downscale percentage, and without the annoying rotation.

My code : 

```dart
await FilePicker.platform
    .pickFiles(
      type: FileType.image,
      allowMultiple: true,
      allowCompression: false,
    );
```

From what I can see, here are example paths : 

**Original file**:

/data/user/0/com.myapp/cache/29074ded-f88f-4adb-b966-ecda82d01aa0/1000012101.jpg

**File copied by `file_picker` plugin**:

/data/user/0/com.myapp/cache/file_picker/1716562208807/JPEG_20240524_165006_8517010291621722032.jpg

**File copied by `image_picker`** when requiring a lower quality: 

/data/user/0/com.myapp/cache/scaled_1000012101.jpg

**Comment by MichaelMarner** [comment]
We are also experiencing this issue, and there are a few aspects.

## Image Compression is stripping exif data

The exif data from selected images is not saved with the compressed version of the image. Most phones use the Exif orientation flag to specify the orientation of the pixel data in the image. This flag, along with all the other exif data, is not saved with the compressed version of the image.

Without the exif data, it's impossible to know what orientation the image is in.

File Picker has two ways forward here - it should either save the exif data with the compressed image, or it should _apply_ the rotation information when saving the compressed image data. My vote is to save the exif data in the compressed image, because it's really useful and if you are picking a file you wouldn't expect the metadata to be removed.

## Android ignores allowCompression

The Android implementation ignores the `allowCompression` flag. This can be seen in [FilePickerDelegate](https://github.com/miguelpruivo/flutter_file_picker/blob/master/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerDelegate.java#L136). The [iOS version does use](https://github.com/miguelpruivo/flutter_file_picker/blob/master/ios/Classes/FilePickerPlugin.m#L237) `allowCompression`.

This makes the results confusing as the documentation indicates that compression is only applied if `allowCompression` is true. This is not the case for Android. Android should bypass compression if `allowCompression` if false.

## A workaround: Set compressionQuality to zero

In the linked line of FilePickerDelegate you can see that compression is bypassed if quality is set to zero. So if you want to workaround this issue, do the following:

```dart
final FilePickerResult? pickedFileResults =
  await FilePicker.platform.pickFiles(
  allowMultiple: allowMultiple,
  type: FileType.image,
  allowCompression: false,
  compressionQuality: 0,
);
```

**Comment by MichaelMarner** [comment]
Oh also regarding quality - the default compressionQuality of 30 is probably too low for most use cases in my opinion. 60 to 80 is more reasonable.

**Comment by q234rty** [comment]
Still seeing this in 8.0.6, would be great if this could be reopened...

**Comment by cuonghoang96** [comment]
still see on 8.3.2
