### ISSUE TITLE
No FileType.CAMERA

### ISSUE THREAD

**Issue by ushang000** [miguelpruivo/flutter_file_picker#157]
can add the filetype for camera ?

**Comment by miguelpruivo** [comment]
@ushang000 was already available in an older version and was intentionally removed because it would force some users that don't use the camera to have the permissions when distributing the apps. Also, you can use this plugin along with the official `image_picker` that allows you to use the Camera to pick files, that's also one of the reasons of why it was removed.

Thank you.

**Comment by ushang000** [comment]
@miguelpruivo 
ok, thank you very much!
