### ISSUE TITLE
This doesn't give the original path of picked file

### ISSUE THREAD

**Issue by rahulserver** [miguelpruivo/flutter_file_picker#182]
The plugin just gives a cached copy of whatever file is selected. Its very confusing and should be explicitly mentioned in documentation. 

Would be great if there is a way to get the actual path of the original "picked" file.

**Comment by miguelpruivo** [comment]
@rahulserver there is already a discussion regarding this on #169.

On Android, basically, the plugin always tries on best effort to get the real path from the file, unless for some reason is protected or from a remote end where it needs to be cached. On iOS this never happens and it is _always_ used a copy from the original file, just like in any other iOS application, as it immediately makes a copy of its contents to the app's own content folder.

I'm planning to make it _always_ a cached file on Android as well to make it more clear and provide a way to get the original Android file URI so the devs can manipulate the original file directly on their own (read, write, etc.). Getting the real path for all files on Android is a pain to not say impossible currently, due to the Android's fragmentation and custom firmware versions available that sometimes don't provide you with the file path _at all_.

**Comment by rahulserver** [comment]
@miguelpruivo shouldn't this be explicitly mentioned in the plugin docs/home page?

**Comment by miguelpruivo** [comment]
@rahulserver typically iOS developers won’t expect files to be the original as its not supported natively and on Android most of the times you should be handling the absolute path unless one of the above reasons happen (most of the time being files from cloud services, thus, caching is always required). It can make sense on the docs nevertheless. However, currently, when caching is made, there are logs proving that info.
