### ISSUE TITLE
Can't find a valid activity to handle the request.

### ISSUE THREAD

**Issue by yostrokon** [miguelpruivo/flutter_file_picker#213]
When using whatever package to request the permission on storage i receive this error
E/FilePickerDelegate(22922): Can't find a valid activity to handle the request. Make sure you've a file explorer installed.

await PermissionHandler().requestPermissions([PermissionGroup.storage]);

or on later check for permissions in another part of the app - the plugin screen opens

**Issue details**
1. Platform Android
2. Q
3. any
4. any storage permission handling procedure used with file picker in the same app

**Error Log**
E/FilePickerDelegate(22922): Can't find a valid activity to handle the request. Make sure you've a file explorer installed.

[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-BG)
    • Flutter version 1.12.13+hotfix.8 at /Users/yourii/Development/flutter
    • Framework revision 0b8abb4724 (5 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/yourii/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

**Comment by yostrokon** [comment]
Steps to reproduce
pubspec.yaml
  permission_handler: any

the source
import 'package:flutter/material.dart';
import 'package:permission_handler/permission_handler.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: PermissionWidget()
    );
  }
}

class PermissionWidget extends StatefulWidget {
  @override
  _PermissionState createState() => _PermissionState();
}

class _PermissionState extends State<PermissionWidget> {

  @override
  void initState() {
    super.initState();
    PermissionHandler().requestPermissions([PermissionGroup.storage]);
  }

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

everything works as expected

1. add file picker into pubspec
  permission_handler: any
  file_picker: ^1.5.0+2
2. uninstall app from device
3. rebuild and run app
E/FilePickerDelegate(29089): Can't find a valid activity to handle the request. Make sure you've a file explorer installed.

**Comment by miguelpruivo** [comment]
@yostrokon is this solved? You mentioned that everything works as expected in your last message. I’m not quite sure if it does or not.

However, make sure you are running the latest version. Since V2 Android support was added, it’s quite hard to have those kind of exceptions because _all_ entry points should be covered.

**Comment by yostrokon** [comment]
solved by moving to 1.4.3+2

**Comment by miguelpruivo** [comment]
@yostrokon the plugin is made in a way that you don't need to explicitly ask for storage permissions in your app. All required permissions are handled from the plugin itself.

Could there be a conflict with it?

Moving down a version is not actually a definite solution since 1.5.0 introduces important additions for Android (V2 embedded).

Thanks.

**Comment by yostrokon** [comment]
Yes, this is a very nice, but part of my app have functionality to save files to the local storage for the later use. User may never use the part with the file picker, but will use the part with the download and save where i have to ask for permission.

**Comment by miguelpruivo** [comment]
This is not the first time it conflicts with Permission Handler. I’ll have to take a look. Thanks.

**Comment by yostrokon** [comment]
It's not permission handler only, i tried with other packages with the same result;

**Comment by miguelpruivo** [comment]
There are people having this issue with permission handler but it looks like a leak from it (when you cancel the request). You can see the discussion regarding this [here](https://github.com/Baseflow/flutter-permission-handler/issues/84#issuecomment-602298326).

Plugins asking for same intents may have collisions and it’s up to all of them to handle the requests properly, otherwise it won’t be easy to find which is actually causing the issue in a project with a bunch of dependencies.

I hardly doubt that a leak could currently be caused on file picker side, after 1.5.0+2 due to the V2 support, but if proved otherwise, I’d be glad to help and fix it.

**Comment by miguelpruivo** [comment]
@yostrokon an user might have found the solution for this issue as described [here](https://github.com/Baseflow/flutter-permission-handler/issues/84#issuecomment-603046729).

Feel free to reopen this if the issue still persist after applying the linked solution.

Thank you!
