### ISSUE TITLE
NumberFormatException in getForApi19

### ISSUE THREAD

**Issue by DenchikBY** [miguelpruivo/flutter_file_picker#221]
Hi! Sometimes I get exception like that when id isn't int, but file's name.

![Selection_344](https://user-images.githubusercontent.com/5912200/77937839-90af1480-72bd-11ea-985d-221f1338e55f.jpg)

https://github.com/miguelpruivo/flutter_file_picker/blob/8eb61af343b988bf0c523263199c53f6bfd2480b/android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java#L72

**Comment by miguelpruivo** [comment]
I wonder why the name is being used as id, which doesn't makes much sense. How can I replicate this?

**Comment by DenchikBY** [comment]
> I wonder why the name is being used as id, which doesn't makes much sense. How can I replicate this?

I don't know, just saw it in crashlytics logs.

As solution I think you can not use `ContentUris.withAppendedId` and just append id to uri:
`Uri.parse(contentUriPrefix).buildUpon().appendPath(id).build();`

**Comment by miguelpruivo** [comment]
Fixed with 1.6.3+2. 

After further investigation it looks like some files (specially those from Downloads folder) after Android Q can't be handled properly and scoped storage (see #234) should be the way to go — you can see [here](https://github.com/Yalantis/uCrop/issues/318) a similar issue and it's discussion. 

For now, there's no immediate way to probably retrieve the absolute file path for those edge cases, but at least, won't crash the app with an exception.

Thanks for reporting.
