### ISSUE TITLE
can't 

### ISSUE THREAD

**Issue by gaoyong06** [miguelpruivo/flutter_file_picker#238]
Thanks to the author, complete such a useful plugin. 

The feature I want to implement is this: 
1. after entering the album, If you select a picture for the first time after entering the album, you can select up to 9 pictures.

2.  if the first time you select a video, only 1 video can be selected. 

3.  If the selected file is selected before you enter the album again after selecting it (whether it is a video or a picture) it is selected. 

4.  Selected files can be clicked to enter the "Details Page" in the upper right corner of the "uncheck" button, that is: you can deselect on the "Details page". 

The question is, when I implement Feature 1 now, I find that I can't choose, where did I not do it?

![GZTDS_P9B$OF{H@_P5}9EFI](https://user-images.githubusercontent.com/1861256/79042038-d907f400-7c26-11ea-8335-07f7a62faa86.jpg)
![H%V8 5PG(65B8YJ_)(HWGTF](https://user-images.githubusercontent.com/1861256/79042039-dc9b7b00-7c26-11ea-8572-fca083413cde.jpg)

**Comment by miguelpruivo** [comment]
Hi and thank you @gaoyong06.

I'm not quite sure if I understood what you are asking for, but I'm afraid that what you requesting is not possible, due to limitations of explorers. File picker doesn't render a custom view but instead calls native platforms (iOS & Android) to launch a native view with OEM pickers, those are stateless and won't keep a reference for the next launch.

As for the limit of items picked (if that's you are also asking on your first point), it can definitely be added and will probably be in a future.

Thank you!
