### ISSUE TITLE
FileType.CUSTOM does not work with any file extension

### ISSUE THREAD

**Issue by kinex** [miguelpruivo/flutter_file_picker#24]
In my app I need support for .csv and .dat file extensions (dat is a backup format in my app, it is actually a zip but I want to separate it from other zip files by file extension). Neither csv or dat seems to work with file_picker (tested in Android). Is there some platform limitation for that "custom" is not actually custom, but it is still limited to few well known file types like pdf, zip etc. If possible it would be much better that file_picker allows any file extension and just filters files by that.

**Comment by miguelpruivo** [comment]
Hi. I understand what you’re trying to achieve, but for that a custom File Provider and explorer would probably be needed, which isn’t actually the purpose of this plugin. 

This is intended to use the native explorers with filters for the supported MIME types on Android or UTI’s on iOS. 

If the file you want to open is not supported, you can always choose ALL which will display all the files without filtering and validate it yourself within the app (e.g. if the returned file doesn’t match the required extension show a warning and open picker again).

**Comment by kinex** [comment]
OK I understand. I think I can live with this limitation, I will use ALL as you suggested.

**Comment by karnadii** [comment]
+1 I need to pick .json file too

**Comment by miguelpruivo** [comment]
@karnadii you should be able to pick json extension by doing: 
```
FilePicker.getFilePath(type: FileType.CUSTOM, fileExtension: 'json’);
```
Have you already tried?

**Comment by karnadii** [comment]
@miguelpruivo i have , 
```
 [FilePicker] Platform exception: PlatformException(FilePicker, Unsupported filter. Make sure that you are only using the extension without the dot, (ie., jpg
instead of .jpg). This could also have happened because you are using an unsupported file extension.  If the problem persists, you may want to consider using FileType.ALL instead., null)

```

**Comment by miguelpruivo** [comment]
@karnadii, that’s weird because json is supported content file type. Is this happening on iOS, Android, or both? Can you check that?

Thank you.

**Comment by karnadii** [comment]
@miguelpruivo using android, yes i use `FileType.ALL` and then validate it within the app

**Comment by karnadii** [comment]
I dont have iOS so I can only confirm for android

**Comment by miguelpruivo** [comment]
Right. I’ll take a look into it whenever I got some time. Thank you @karnadii.

**Comment by pcegarra** [comment]
Maybe the filetype should be an array of files types.

**Comment by miguelpruivo** [comment]
@pcegarra yes, that’s one of the upcoming requested features.

**Comment by jamesmoore255** [comment]
@miguelpruivo when do you think the array of file types will be supported?

**Comment by miguelpruivo** [comment]
@jamesmoore255 I got have to have some time to implement it, I can't really tell. Can be this week, can be this month... 😞 But it's definitely the next feature to add to this plugin.

Sorry for taking a while.

**Comment by jamesmoore255** [comment]
No problems @miguelpruivo, I'll keep an eye out for when it is finished!

**Comment by Zeeshan0201** [comment]
@miguelpruivo it's implemented(array of file types ) or still remaining?

**Comment by miguelpruivo** [comment]
It’s on the todo list @Zeeshan0201

**Comment by Zeeshan0201** [comment]
@miguelpruivo okay, please let us know when it's completed.thanks in advance.

**Comment by FineTillYouCameAlong** [comment]
Will I be expected to provide all purpose strings on iOS if I use FileType.ALL? My app is using FileType.ALL (because of unsupported extensions) and when I tried to upload my binary to the App Store, it got rejected because it was missing the NSPhotoLibraryUsageDescription purpose string in Info.plist.
I don't know where/how these purpose strings show up (because I've been using the app only on my test device where everything goes) but it would be a significant disadvantage to using FileType.ALL as a workaround for unsupported extensions.

**Comment by miguelpruivo** [comment]
@FineTillYouCameAlong you are using a package that allows you to access the gallery thus you need to provide the proper entitlements for that because Apple doesn’t know if you’ll actually be picking files from it. 

That will happen with every package that uses any kind of functionality, however, the user won’t be notified or allow those permissions unless you explicitly use it on your app.

**Comment by Laban1** [comment]
I am having a similar issue, but unable to use the FilePicker at all (Android emulator).

First I tried:

    var path = FilePicker.getFilePath(type: FileType.CUSTOM, fileExtension: 'json’);

"Unsupported filter. Make sure that you are only using the extension without the dot, (ie., jpg instead of .jpg). This could also have happened because you are using an unsupported file extension.  If the problem persists, you may want to consider using FileType.ALL instead."

    var path = await FilePicker.getFilePath(type: FileType.ANY);


"No implementation found for method ANY on channel file_picker"

What I need is to prompt the user to pick a json file from a folder under getExternalStorageDirectory().path:

    var backupPath = join((await getExternalStorageDirectory()).path, 'archive');


_Is this even supported (how do I specify that the file to pick is in backupPath)?_

Sorry to ask two questions in the same post, but they are related and help would be much appreciated...

**Comment by arkanmgerges** [comment]
Hi, I also wanted to get may backed up sqlite db, I've used FileType.CUSTOM and fileExtension: "sqlite", and fileExtension: "db", and both of them did not work.
Even I've used FileType.ANY and it does not show my backup_db.sqlite file even I tried backup_db.bin and backup_db.sqlite, and none of them worked for me.

**Comment by romathebest** [comment]
hi, any news about the fix? I still have this issue on version 1.5.0+2

**Comment by miguelpruivo** [comment]
@romathebest not yet, there are a couple of things on the line to be made, however, this plugin uses the supported UTI's, I'm not quite sure why it wouldn't support some files. Which type are you trying and in which platform/device? Thank you.

**Comment by romathebest** [comment]
I am trying to show only .db files with SQLite data. Android 10 - Samsung s9 sm g960f

**Comment by Adem68** [comment]
I'm using 1.5.1 version. I can't show only kml and gpx files with `custom` parameter.

`FilePicker.getFilePath(type: FileType.custom, fileExtension: 'GPX');`
`FilePicker.getFilePath(type: FileType.custom, fileExtension: 'KML');`

Library gives platform exception;

`Platform exception: PlatformException(Unsupported file extension, Make sure that you are only using the extension without the dot, (ie., jpg instead of .jpg). This could also have happened because you are using an unsupported file extension.  If the problem persists, you may want to consider using FileType.ALL instead., null)`

I was using `any` parameter at old version and it's was working.

`FilePicker.getFilePath(type: FileType.any, fileExtension: 'GPX');`
`FilePicker.getFilePath(type: FileType.any, fileExtension: 'KML');`

Should may i downgrade version?

**Comment by romathebest** [comment]
@Adem68 it's not working for a while, this issue opened more then a year ago
Right now you can use only FileType.any for files with your custom extensions

**Comment by Adem68** [comment]
Thx for reply @romathebest i tried with FileType.any then not worked.

**Comment by miguelpruivo** [comment]
@Adem68 you need to use `FileType.any` and don't specify an extension at all. That's on the Wiki.

**Comment by romathebest** [comment]
@miguelpruivo I have checked code. There is getMimeTypeFromExtension() on android and it has limited extensions support. It changed in each version of android. For example, you can check list for [android 7](http://aosp.opersys.com/xref/android-7.1.2_r11/xref/libcore/luni/src/main/java/libcore/net/MimeUtils.java) 

I think there should be work around not to use it and set extensions manually

**Comment by miguelpruivo** [comment]
@romathebest sure, that's what this issue is all about, actually.

**Comment by DebugTheCode** [comment]
As a suggestion, if you want to manually check what codec a file is, you can use the ffmpeg library (https://pub.dev/packages/flutter_ffmpeg). For some things it may be an overkill to use it, but it's very reliable.

**Comment by miguelpruivo** [comment]
@DebugTheCode I'm familiar with ffmpeg, however, it's an heavy package to be bundled with and also has restrictions on minor iOS version for Flutter (I believe iOS 11). I think that it should be up to the user to use whatever he wants because some may want to add compression, check codecs and so on while others don't.

**Comment by DebugTheCode** [comment]
@miguelpruivo I agree. That's why I warned for the possible overkill.

**Comment by wreyford** [comment]
> @miguelpruivo I have checked code. There is getMimeTypeFromExtension() on android and it has limited extensions support. It changed in each version of android. For example, you can check list for [android 7](http://aosp.opersys.com/xref/android-7.1.2_r11/xref/libcore/luni/src/main/java/libcore/net/MimeUtils.java)
> 
> I think there should be work around not to use it and set extensions manually

I looked at the link supplied, and on line 314 the 'csv' type is an included mime type, yet your file picker refuses to see the *.csv extension when used with custom. I need to limit users to the correct file type. Whats the use of a file picker with extensions if the appear greyed out. Changing the extension of the file to .xls makes it visible to the file picker if .xls is used as the extension, but remains greyed if csv. Why can this not be fixed on your side.

**Comment by miguelpruivo** [comment]
@wreyford the plugin just acts as a bridge between Flutter and iOS/Android by launching their own pickers with a few parameters one of which is the file type filter. Thing is, some Androids will honor those filters whereas others don't, you can read moer about it [here](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting#-issue-1).

Think of the filtering as a nice to have but you should always validate on your side, thus, discarding all unsupported files. I can't by any means force whatever file explorer will launch with the picker, to accept/refuse those filters, because some users even have 3rd party explores such as ESExplorer that can be used along with file picker.

**Comment by Aravin** [comment]
There is no fix for this bug, but it was closed ?

**Comment by miguelpruivo** [comment]
@Aravin that’s just a platform bottleneck. There’s no definite fix that can be applied here other than creating a custom explorer from scratch which wasn’t the intended behavior from the plugin since the beginning.

I’m sorry for any inconvenience.

**Comment by mohammed710** [comment]
just write this 
![a](https://user-images.githubusercontent.com/84449047/208302208-3552cbe9-97bb-4455-9e73-614152600c86.png)

**Comment by charismatest** [comment]
I am trying to filter 'bin', but get this error. I tried a few other extensions like 'jpg' and 'pdf' and they seem to work. I don't quite understand which MIME types are currently supported, would be nice to have a list or something.
