### ISSUE TITLE
[Feature] Multi file pick to set length to be fetch.

### ISSUE THREAD

**Issue by SureShDood** [miguelpruivo/flutter_file_picker#246]
I encourage you to add new suggestions that you think that can make file_picker even a better package.

_**Note:**_: Before creating a new suggestion, make sure it isn't already listed. Filter by [suggestion] tag.

**Comment by miguelpruivo** [comment]
This might be a good suggestion, however, on Android it will force `minSdk` version to increase to 18 (currently 16 is min supported).

**Comment by miguelpruivo** [comment]
Assuming that it should be fine to change Android's `minSdk` from 16 to 18 for everyone, I'll consider this suggestion as a future feature as it might bring value to the package to some users.

Thanks!

**Comment by miguelpruivo** [comment]
After further investigate this, I came to the conclusion that this is not fully supported by both platforms and should be handled by the developer itself. This is, if your user picks more than your max established number of elements, just discard them and display an alert.

The same applies for file size limit while picking. If as of today is still hard to ensure reliability of restricting the allowed extensions due to 3rd party pickers, with this, it could even get worse and we may end up with a lot of _non_ reliable features, which I don't want.

Anyhow, thank you for your suggestion! 😃
