### ISSUE TITLE
Files accessed via Seafile Cloud is not possible to write to

### ISSUE THREAD

**Issue by predme** [miguelpruivo/flutter_file_picker#253]
Before creating an issue, make sure that you are on the latest `file_picker` version and that there aren't already any similar opened inssues. Also, check if it isn't described on the [Wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki), specially on [Troubleshooting](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting) page.

Also, sometimes a simple `flutter clean` and `flutter build` again with latest file_picker version, may end up by fixing cached issues, so I encourage you to first do so.

**Describe the bug**
I've been trying to access files on my Seafile server with mixed results. I've been able to retrieve the file and read from it in my app, but when I try to save to the file, weird stuff happens. It appears to be writing the data somewhere, but when I check the file I opened in Seafile via the native file manager, I can see that no data has actually been written to it.  Looks like I'm writing to some temporary file or cache? And of course, files that are on the internal storage gets read and written to like expected.

**Issue details**
1. Android
2. Android 10 API 29
3. XML
4. Open the file picker, navigate to the Seafile storage, then pick the appropriate file (in my case, a XML). I'll be able to read the file and seemingly write to it without actually writing to the file. While writing this, I decided to check what the path of the file actually is within my app and it looks like my suspicion is correct. Here's the file I'm given when I access my file via Seafile:

/data/user/0/me.pred.imperium/cache/ImperiumLogBackup.xml

So it appears to be cached in my app directory and not actually writing to the source file.
I'm not sure if this is intentional or not but I'm assuming you should be able to write to the cloud files, correct?

**Flutter Version details**
```
[✓] Flutter (Channel master, v1.18.0-6.0.pre.83, on Linux, locale en_US.UTF-8)
    • Flutter version 1.18.0-6.0.pre.83 at /home/vlad/Documents/Git/flutter
    • Framework revision 8e5b575174 (4 days ago), 2020-04-19 17:20:01 -0400
    • Engine revision 2b75c6d111
    • Dart version 2.9.0 (build 2.9.0-1.0.dev 4814f000de)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /opt/android-sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /opt/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```
I apologize for not having the device available.

**Comment by miguelpruivo** [comment]
Hi @predme, and yes, most of the times, specially in later Android SDKs, files will be cached as they don't want us to use absolute file paths to handle it — instead, they want use to use scoped storage with URI's but that doesn't allow users to open descriptors using `File` object on Dart side, which is most of the time desirable. So, because of that, I've a planned feature that I have already an issue purposed on #234 to support both.

When this plugin was made, its initial purpose was to have a reliable way for users to pick content (media, files, etc.) and use on their apps, most of the times to upload somewhere and so on, while ensuring file safety, hence, cached files shouldn't affect most — on iOS, you are actually forced to use cached copies.

I'll close this as it's related to #234, but we can still discuss any further details there.

Thank you!
