### ISSUE TITLE
cannot build ios version 1.7.0

### ISSUE THREAD

**Issue by Dreamersoul** [miguelpruivo/flutter_file_picker#255]
when i build the application i get the following error:
```
[!] CocoaPods could not find compatible versions for pod "file_picker":
      In Podfile:
        file_picker (from `.symlinks/plugins/file_picker/ios`)

    Specs satisfying the `file_picker (from `.symlinks/plugins/file_picker/ios`)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by miguelpruivo** [comment]
Thats because since 1.7.0 introduced a new feature and you need to set minimum version of 10.0 on iOS. That's on the changelog and Wiki as well.

Nevertheless, that new feature (see #233) will be replaced with a new one and you will be able to have iOS 8.0 as minimum again. For now, if you don't want to change versions, just stick with 1.6.3+2.

**Comment by Dreamersoul** [comment]
thank you, that fixes it 👍
