### ISSUE TITLE
The parameter that specifies the maximum number of files in the getMultiFile method, Problem displaying empty loading dialog in ios

### ISSUE THREAD

**Issue by cs-hyunseo** [miguelpruivo/flutter_file_picker#287]
Are you planning to add a parameter to specify the maximum number of files in the getMultiFile method? Currently, there are unlimited choices, which can put a load on the server. I would like to limit this.

And when selecting multiple files in ios, an empty loading dialog is displayed. After selecting the file, the functions proceed normally, and I think this dialog box has no effect on providing information because no text and progress bar is displayed. Can I optionally remove it?

**Comment by miguelpruivo** [comment]
@cs-hyunseo hi, I’ve not yet implemented this because there’s no reliable way to do so on Android. There will be some explorers that honour the max limit whereas other don’t.

You can easily discard any N items after being picked as you receive a map with all of the and then easily check its length against your desired maximum.

This way, you can let your user do whatever you want to and/or even show an error message. I can set a limit parameter and do it for you, but I believe that’s better to let the dev do whatever he wants.

**Comment by miguelpruivo** [comment]
Close as dup of #118

**Comment by skiryuk** [comment]
> Закрыть как дуп [№ 118](https://github.com/miguelpruivo/flutter_file_picker/issues/118)

I look at the multi_image_picker package and see that there is a maxImages option. 
Is it possible to do by analogy, e.g. maxFiles ?

**Comment by miguelpruivo** [comment]
@skiryuk I’m sorry, but this hasn’t been implemented only because it isn’t reliable on Android. That package probably uses a custom file explorer (I believe it does from other 3rd party plugins) instead of letting the user use its own (file picker only requests an intent for picking the files with the filter).

That means that some might honour whereas others don’t, and cause potential issues due to its inconsistency.

That’s the only reason why it hasn’t been added. On iOS, on the other hand, it works just fine, but it wouldn’t make much sense to add the feature on iOS and not on Android. It’s either all or nothing IMO.

Thank you for your comprehension.
