### ISSUE TITLE
Filetype camera not found.

### ISSUE THREAD

**Issue by joshipucher** [miguelpruivo/flutter_file_picker#309]
Hello.

I tried this version of the plugin, as it also should include the function to open the camera and get the file from there.
https://pub.dev/packages/file_picker/versions/1.2.0#-example-tab-

Unfortunately, this line of code
`final imageFile = await FilePicker.getFile(type: FileType.camera);`
give me the error message "There is no constant named 'camera' in 'FileType'."

So isn't it implemented yet?
If you still working on it, it would be nice to be able to open the gallery and in the gallery have another button to open the camera. Similar to Instagram e.g.

**Comment by miguelpruivo** [comment]
As you can [see here](https://github.com/miguelpruivo/flutter_file_picker/blob/master/file_picker/CHANGELOG.md#130), with camera support was removed back on 1.3.0 because some user reported to have camera mandatory entitlements on Android when publishing to the store.

That would mean that despite not using camera feature at all, if your app has camera picking support, on Android, it would inform the users that the app may use camera features which for some is undesired as may rise privacy doubts (specially when the app itself doesn't actually uses it).

Because of that, I opted to leave the camera support behind and let users combine `file_picker` with `image_picker` whenever the need the camera.

As of today, I'm still not sure whether I should revert back and add camera support or not to it. On one side, it will be a plus for some users, but also a downside for others.

**Comment by joshipucher** [comment]
thanks for the quick explanation!
so if i use the camera from image_picker, I also may get a problem when publishing to the store?

i prefer your plugin because you can choose images and videos with one command. 
the most preferable would be to have image/video picker with the option to record an image/video by clicking a button when viewing the library, so that no dropdown is needed to select if you want to record or pick etc. But if it's not easily possible I will use the dropdown for now.

**Comment by miguelpruivo** [comment]
You won't have a problem because you will actually use the camera as intended. The issue rises for developers that would have to use `file_picker` without _ever_ needing the camera, and then, when installing from the PlayStore, there would be an info telling the users that the app _may_ use camera permissions because it can actually analyze binaries and detect that your app have camera access.

This way, you have a more modular control and use different plugins for each task. Even on my own apps, I end up using a dropdown or action sheet picker to let users pick from camera and/or files and mix both plugins.
