### ISSUE TITLE
App crash on file pick in android

### ISSUE THREAD

**Issue by q200892907** [miguelpruivo/flutter_file_picker#313]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
at com.mr.flutter.plugin.filepicker.FilePickerDelegate$2.run(FilePickerDelegate.java:161)

Quick dirty hot fix:
在FilePickerDelegate.java 修改type字符串判断，因为type有时候会出现null情况

**Comment by miguelpruivo** [comment]
Hi, before opening an issue, please check the troubleshooting section on the wiki to see if there's any solution for your problem.

This one, particularly, is right exactly the first one [described here](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting#-issue).

Thanks.

**Comment by q200892907** [comment]
我这里遇到此问题后，对type字符串判断方式进行修改后不会崩溃了。

**Comment by q200892907** [comment]
暂时未追到出现type = null 的原因，进行断点调试发现进入了3次选择完成回调方法，最后一次type变为null ，程序崩溃

**Comment by miguelpruivo** [comment]
Sorry, I don't want to sound harsh, but I don't get what you're saying. This Github project typing language is set to english only so anyone can follow the issues (otherwise I'd be typing in portuguese as well 😃).

**Comment by miguelpruivo** [comment]
Anyway, you just need to upgrade your Flutter version to latest stable (run `flutter upgrade`) in order to fix that issue.

**Comment by q200892907** [comment]
Please modify the FilePickerDelegate.java file
type.equals("xxxxx") => TextUtils.equals(type,"dir")
Perform safe string identical judgment

**Comment by miguelpruivo** [comment]
@q200892907 `type` is never `null` there, so `type.equals()` is perfectly correct, there's no need to add `TextUtils.equals` which will mostly add a `null` check. You have an issue because you are with an old Flutter stable version (mostly like below 1.17).

Update it and you'll be fine.

**Comment by q200892907** [comment]
So it is not compatible with the old version of flutter?
Okay, I know

**Comment by obiwanzenobi** [comment]
I've got the same problem with the newest Flutter version (stable 1.17.5) but only on Xiaomi devices (Redmi Note 7).

**Comment by robson-cervantes** [comment]
I've got the same problem with flutter version 1.20.1 stable in Moto G5 S Plus. 

Testing the lib, I realized that the call `this.activity.startActivityForResult (intent, REQUEST_CODE);` of the `FilePickerDelegate` class triggers the `onDestroy()` method of the `FlutterActivity` class. Because of this, when the ActivityResult is returned, the code `GeneratedPluginRegistrant.registerWith(this);` in `onCreate` method is called again, that reset FilePickerDelegate instance. So, when the thread inside the `onActivityResult` method is called, the value of the `type` attribute is `null`, as it has been reset. 
Furthermore, if I debug the entire process step by step, the onDispose method is not called. 

Anyway, I have this problem and I hope this report helps something.

**Comment by vinicios-cervantes** [comment]
@robson-cervantes go to your developer options and disable don't keep activities option

**Comment by robson-cervantes** [comment]
@vinicios-cervantes really the problem was this, disabling the option returns to work normally. Thank you !!

**Comment by miguelpruivo** [comment]
Thank you for your input @vinicios-cervantes I’m not familiar with those Android device’s nuances as I’ve been an iOS user since I can remember.

This may fit on the wiki as well to help out other users.
