### ISSUE TITLE
allow customization of native pickers

### ISSUE THREAD

**Issue by jamesdixon** [miguelpruivo/flutter_file_picker#321]
Me again 😄 

Is it possible to customize the underlying appearance of DKImagePicker on iOS? When you select multiple images it numbers them, but the numbers are difficult to see when the image has a bright/light background. Here's an example:

![IMG_FE1A04555653-1](https://user-images.githubusercontent.com/110114/87207523-4af4e580-c2c9-11ea-8e9f-2b9ae177c324.jpeg)

On the DKImagePickerController page, it shows an example like this:

![image](https://user-images.githubusercontent.com/110114/87207554-5ba55b80-c2c9-11ea-8f2d-609d99198163.png)

**Comment by miguelpruivo** [comment]
Hi @jamesdixon as you can see [here](https://github.com/zhangao0086/DKImagePickerController/issues/653) 3 months ago I asked the lib owner about how to do it the easy way so I could expose it for devs using the the plugin.

But as you can see, the answer was a little bit far from what I expected. So I ended up not doing anything but mostly because no one explicitly asked for it, as you’re doing right now. 😃

So yes, I’ll probably figure a way to pick from 2 or 3 different options easily on plugin side.

**Comment by jamesdixon** [comment]
@miguelpruivo Hello! sorry for my delayed reply on this. Somehow I completely missed your response.

Ah, gotcha! Yes, not much of a response.

That would be great. Even just having the default option as the one with the outlined squares would be helpful. My guess is that most don't care about the look itself but I'm certainly just making an assumption. For me it was just the clarity of what had been selected.

Thank you and hope all is well!

**Comment by miguelpruivo** [comment]
@jamesdixon sorry, I just hadn’t the time yet to look into this — can’t actually wait for my vacations to start so I can take care of a few personal projects such as this one 🙌 — if you’re on a rush and manage to easily implement it, feel free to issue a PR, otherwise I’m afraid I can’t promise to have it done before end August, early September (but I will try though! 😅)

**Comment by miguelpruivo** [comment]
Closing as this is a no-op with no ETA. Will re-open if needed.
