### ISSUE TITLE
Cannot access the photo library

### ISSUE THREAD

**Issue by jawad12345A** [miguelpruivo/flutter_file_picker#334]
When i use this method it does not let me choose photolibrary
    File file = await FilePicker.getFile(type: FileType.any);

**Comment by miguelpruivo** [comment]
Please, before opening an issue check the [wiki](https://github.com/miguelpruivo/flutter_file_picker/wiki) because it has detailed information about how to use it.

Photo gallery doesn't contain all types of files. For that, you need to use `FileType.image`, `FileType.video` or if you want both, `FileType.media`.

Thanks!

**Comment by jawad12345A** [comment]
Hi but i want to access images, videos and the files all of them just like i do in android

**Comment by miguelpruivo** [comment]
@jawad12345A I'm sorry to inform you that that doesn't exist on iOS at all. On iOS you only have access to Files app (which is when you use `FileType.any`) or to Photos app (with the types I gave you previously). You can't access both at the same time.
