### ISSUE TITLE
Get link from remote repository instead of pdf

### ISSUE THREAD

**Issue by mbenci** [miguelpruivo/flutter_file_picker#340]
Do you think it could be possibile to get the file link of the remote repository (GDrive, Dropbox, OneDrive)?
Now if I click on gDrive file (for example a Google document or a Google sheet) it is first converted in pdf then this pdf is picked in my application, but I don't want the pdf.

Thanks,
Marco

**Comment by miguelpruivo** [comment]
@mbenci I'm sorry, I don't think we can have permissions for it as those direct resource links (for each 3rd party share file) must be handled by their own providers — this is, on their own app and generating an url, because some providers have different permissions on their files and so on.

Let me know if you find out a way to work around this.

Closing as WAI.
