### ISSUE TITLE
Getting .mov file in IOS PhotoGallary

### ISSUE THREAD

**Issue by kawaldeep2507** [miguelpruivo/flutter_file_picker#342]
In IOS have turn off the compression  and selecting a .mp4 file from the Photo Gallary but still i am getting .mov compressed file. 
File _file = await FilePicker.getFile(
            type: FileType.video, allowCompression: false);
      if (_file != null) {
        String filePath = _file.path.split('/').last;
        _fileExtension = filePath.split('.').last;
        _fileExtension = _fileExtension.toLowerCase();
      }

On the Contrary if i user getMultiFile instead of getFile. I am getting the file in .mp4 format

**Comment by miguelpruivo** [comment]
Hum, so you're saying that compression is working only with multi file?

**Comment by kawaldeep2507** [comment]
What i meant was i want to pick a mp4 format file from IOS Photo gallary but i am getting mov format file instead. 

Even after setting "allowCompression: false"

File _file = await FilePicker.getFile(
type: FileType.video, allowCompression: false);

**Comment by miguelpruivo** [comment]
Ok @kawaldeep2507 I will take a look.

**Comment by kawaldeep2507** [comment]
@miguelpruivo :- Any update regarding this?

**Comment by miguelpruivo** [comment]
@kawaldeep2507 sorry just hadn't the time yet. I'll try today.

**Comment by miguelpruivo** [comment]
@kawaldeep2507 so I ended up looking into it and it turns out it is working as intended. What happens is that iOS natively will export on `MOV` format, but when you use `getMultiFile` it's using a different package internally (DKImageController) which is actually converting to MP4, that's why you get all files on mp4 with it.

Anyway, compression is not happening if you set `allowCompression` to `false`. You can easily test it out because with it set to `true` (which is the default) a little compression bar will fill after picking a video, whereas if you don't allow, it will immediately return (even if the bar shows up briefly).

I could convert all movie files to mp4 anyway, but that's a different task and you can also convert it as well if you want (sometimes even just renaming to .mp4 will work "out of the box" because both formats are very similar codec wise).
