### ISSUE TITLE
Filter by a certain date

### ISSUE THREAD

**Issue by qbait** [miguelpruivo/flutter_file_picker#344]
Are you planning to add the possibility to filter by a certain date?
Currently, I need to implement a video picker that shows videos for the specific date and your lib would be perfect.

**Comment by miguelpruivo** [comment]
Hi! I’d like to please you, but I’m afraid that this isn’t currently supported by the native pickers in a reliable way. Specially on Android where even some file filters aren’t honoured by the picker itself when handled by 3rd party ones.

Because of that, my suggestion is to let the users pick the files and then you may discard those that don’t fit that time window.

In #234 I have plans to introduce a `PlatformFile` abstraction where I may include metadata information such as date and so on.
