### ISSUE TITLE
File limit is selected

### ISSUE THREAD

**Issue by nambdonegroup** [miguelpruivo/flutter_file_picker#353]
Can you add feature max file selected in FilePicker.getMultiFile? 
I need it.
Thanks!!!

**Comment by miguelpruivo** [comment]
This has been discussed multiple times on #64 and #118 and #314. There’s no reliable way to achieve so on Android.

It might work one some but other explorers _may_ ignore and I’d rather have it missing this feature than having people reporting issues because file limit is not respected on some Android devices. 😔

I’m sorry for any inconvenience.
