### ISSUE TITLE
Clarify intended usage with web platform

### ISSUE THREAD

**Issue by wreppun** [miguelpruivo/flutter_file_picker#358]
After reading through a few issues, including https://github.com/miguelpruivo/flutter_file_picker/issues/292 and https://github.com/miguelpruivo/flutter_file_picker/issues/229, and the [readme](https://github.com/miguelpruivo/flutter_file_picker/blob/master/file_picker_web/README.md), I'm still not quite sure how `flutter_web_picker` is intended to be used.

The readme looks very similar to the standard flutter plugin, and suggests that adding `file_picker_web` to the pubspec should be enough to enable the web platform (this is how, for example, `image_picker` works).  Unfortunately, this isn't quite set up to work.

This is blocked by:
- The use of `MethodChannelFilePicker` [here](https://github.com/miguelpruivo/flutter_file_picker/commit/1e78f28220da3f952a74adb630fd2f953ec179de#r41435891).  I thought this would be a fairly straightforward fix, but even if we fix the parameters on the `FilePickerPlatform` interface, we still end up with the issue:
- Web.FilePicker.getFiles(...) returns a List of files, while FilePicker.getFiles (the delegating class) expects either a String or a Map<String, String>.

So, since the flutter plugin architecture doesn't seem to be working here, is the preferred usage to conditionally import the correct package?

Something like 
`import 'package:file_picker/file_picker.dart' if(dart.library.js) 'package:file_picker_web/file_picker_web.dart'

If that's the case, then
- It would be helpful to export `FileType` from the `file_picker_web` package, otherwise the user will have to import `file_picker_platform_interface` as well if the user wants to use the `type` parameter
- The general `file_picker` repo might be able to get rid of the complexity of the PluginPlatformInterface, since it isn't used.

Thanks again for your work on this!

**Comment by miguelpruivo** [comment]
Hi! The idea behind this is exactly that, to have to use only the file picker web alone without any other dependency. If this is not happening, then there could be an issue with it that should be addressed.

Initially I wanted to have only one package and stub all the files accordingly to web/io. However, having common class names on both (`File`) makes it impossible because you need to effectively return one of those types, that’s where the interface comes in play to solve all of this.

I’m sorry that I haven’t had enough time lately to work on this but let me know if you come up with a fix and I’ll be happy to implement/review it.

**Comment by miguelpruivo** [comment]
Do you have any suggestions @wreppun?

**Comment by BirjuVachhani** [comment]
@miguelpruivo You should consider using a wrapper for returning files like other file picker plugins are doing. That way, stubbing would work fine. [Check this out]((https://gitlab.com/testapp-system/file_picker_cross/-/tree/master/lib)). Thought it might help.

**Comment by miguelpruivo** [comment]
@BirjuVachhani thank you, I'll take a look as soon as I have the time.

**Comment by miguelpruivo** [comment]
I will probably work on this during my vacation time which is scheduled for the next week, so you might expect some news. 🎉

**Comment by miguelpruivo** [comment]
FYI: I'm already working on this along with #234, expect a release this week. 🎉

**Comment by BirjuVachhani** [comment]
@miguelpruivo That's great. Looking forward to trying it out.

**Comment by miguelpruivo** [comment]
Update: I’ve had success on its implementation and it’s only missing iOS refactor to include the new changes.  I’m expecting to do so by tomorrow with 2.0.0 release that will include breaking changes (for better) and only file_picker will be required.

From there on, instead of paths and multiple methods, it will be simplified and a `FilePickerResult` will be returned that contains helper getters with relevant data and a `List<PlatformFile>` with the picked files which include detailed data such as name, bytes, path, uri, etc.

Also, on Android it will _always_ create a cached copy of the picked file (just like iOS does) to prevent misleading picks and ensure that everything can actually be picked.

I’ll write a migration guide anyway when deploying. Expect the file_picker_interface and file_picker_web to be deprecated after that. 

Thanks!

**Comment by BirjuVachhani** [comment]
This sounds wonderful. Does this also work for Android's scoped storage?

**Comment by miguelpruivo** [comment]
@BirjuVachhani yes, that’s also one of the focuses.

**Comment by miguelpruivo** [comment]
Update is now live with [2.0.0](https://github.com/miguelpruivo/flutter_file_picker/blob/master/CHANGELOG.md#200) please, [see the changelog for details](https://github.com/miguelpruivo/flutter_file_picker/blob/master/CHANGELOG.md#200) of what have changed.

All platforms are now unified with `file_picker` and this should be the only required dependency.

Let me know if you find any issue!

Thank you!
