### ISSUE TITLE
Expose 'native' file modified time

### ISSUE THREAD

**Issue by nwparker** [miguelpruivo/flutter_file_picker#368]
I've noticed that when inspecting a file's `modifiedTime()`, it will display the datetime when the cached file was created. Is there a way instead expose the modified time from the native iOS/Android side?

🤔 Even a way to expose the native file path would give way to writing a small plugin that could do this.

**Comment by nwparker** [comment]
> @nwparker that may be an interesting part of a property to be introduced with #234.

That'd be cool. Is having scoped storage a blocker for this or are you saying that it just makes sense to add it at that time? Sorry, I'm new to this! If it is a blocker, are there similar blockers for iOS?

**Comment by miguelpruivo** [comment]
It makes sense to add it by the same time because I’ll need to create an object to act as wrapper such as `PlatformFile` or so which may include amongst others, things such `originalPath`, `cachedPath` etc.

**Comment by nwparker** [comment]
> It makes sense to add it by the same time because I’ll need to create an object to act as wrapper such as `PlatformFile` or so which may include amongst others, things such `originalPath`, `cachedPath` etc.

Oh, gotcha. Makes perfect sense!

**Comment by miguelpruivo** [comment]
FYI: I'm already working on this along with #234, expect a release this week. 🎉

**Comment by miguelpruivo** [comment]
**Update:** [check comment](https://github.com/miguelpruivo/flutter_file_picker/issues/358#issuecomment-690812563).

**Comment by miguelpruivo** [comment]
Update is now live with [2.0.0](https://github.com/miguelpruivo/flutter_file_picker/blob/master/CHANGELOG.md#200) please, [see the changelog for details](https://github.com/miguelpruivo/flutter_file_picker/blob/master/CHANGELOG.md#200) of what have changed.

The native modified time I'm afraid isn't possible. After researching, most of the time only cached times will be given (when the file is cached on the user app content) which means that could result in misleading `lastModifiedDate`. I had it implemented (you can see the commits) but ended up removing because most of the times the time was just the time the file was first picked and not when it was created.
