### ISSUE TITLE
[Feature] Use gallery view for image and video files

### ISSUE THREAD

**Issue by sidrao2006** [miguelpruivo/flutter_file_picker#370]
# Use Case

Flutter's image picker uses the native gallery to pick images and videos. This feature is very useful, but for some cases we would also need to pick other file types. This feature can be integrated by depending on image_picker, or implementing it directly.

**Comment by miguelpruivo** [comment]
Hi! This has been done before in early versions of file picker and then removed because depending on other Flutter packages should be avoided — imagine there’s an issue with it and you are stuck until they fix it, besides, it includes camera pick and other features that some users don’t want to include at all — actually, it was removed because of that, there was some user that had to Include camera entitlements when publishing to the store even thought the app didn’t used the camera at all (just because the picker had it).

Last but not least, this also uses the native gallery for picking both videos and images, so there’s no reason why, using it as dependency will also bring all of its issues along with it.

Thank you!

**Comment by sidrao2006** [comment]
Ok thanks @miguelpruivo 
However in the documentation, according to the images and clips, the package doesn't use the native gallery, rather it uses the file explorer with filters.
If this package does support picking images and videos in native gallery then that's really good. Can you please confirm? 
Thank you

**Comment by miguelpruivo** [comment]
@sidrao2006 it supports. Just set the `type` To `FileType.image`,  `FileType.video` or `FileType.media`. However, have in mind that only works for single picks not multi because iOS doesn’t support multi picks in the native picker.

**Comment by sidrao2006** [comment]
Ok, thanks a lot
