### ISSUE TITLE
List of allowed extensions should be mentioned in the documentation

### ISSUE THREAD

**Issue by haroonkhan9426** [miguelpruivo/flutter_file_picker#393]
List of allowed file extensions is missing from the documentation exception mentioned few in some examples. It will be more intuitive if you can add a list of allowed file extensions in the documentation.

**Comment by miguelpruivo** [comment]
@haroonkhan9426 there are lot of types which are actually mentioned in the wiki [here on the troubleshooting page](https://github.com/miguelpruivo/flutter_file_picker/wiki/Troubleshooting#-possible-solution-1) if you click on the MIME link.

It should assume most of the common extensions, however, have in mind that it’s up to Android explorers to honor or not the requested filters (which unfortunately some don’t).

But I might make it more explicit on the wiki instead of the troubleshooting area.

Thank you!
