### ISSUE TITLE
Accessing the Uri of the file 

### ISSUE THREAD

**Issue by shaan-mephobic** [miguelpruivo/flutter_file_picker#478]
I know we can't use the file from the directory where the file is in ,so this plugin caches the file in the app. It really would help me if it was possible to access the Uri as a few features in kotlin(my app needs a few platform specific code) needs the uri of the file to work. Or is it possible to get the uri of the file cached ?

**Comment by miguelpruivo** [comment]
@shaan-mephobic I had the URI on my first 2.0.0 draft implementation. However, I removed it since I assumed that most people wouldn't use it and would probably starting to open issues saying that can't open the URI (instead of the path).

TL;DR: It's possible to add it, yes, I'm just not sure on how to make it clearly that you can't use it with `File` instances.
