### ISSUE TITLE
Build failed with an exception

### ISSUE THREAD

**Issue by chris-pro** [miguelpruivo/flutter_file_picker#489]
Hello,

After updating the package to version 2.0.12, I can no longer launch my application in debug mode (on Android 10 and Android 8) or build an apk.
I tried the "flutter clean" and "flutter build apk" commands
I also tried to create a new empty project, but the problem persists.

- Flutter version 1.22.3 (stable channel)
- I was previously using version 1.12.0 of file_picker which worked fine.
- I have of course made my source code compliant with version 2

### log
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     D:\Documents D\Dev\memorize\android\D\Dev\memorize\build\file_picker\intermediates\library_manifest\debug\AndroidManifest.xml:9:5-15:15: AAPT: error: unexpected element <queries> found in <manifest>.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
√ `android\settings_aar.gradle` created successfully.
Building plugin file_picker...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'file_picker'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

Exception: The plugin file_picker could not be built due to the issue above.
Exited (sigterm)
```

Thank you in advance for your help.

**Comment by miguelpruivo** [comment]
Hi @chris-pro this is related/dup of #481 somehow. This issue is likely to compatibility issues with Android X migration.

I suggest you to take a look to the [official migration guide](https://flutter.dev/docs/development/androidx-migration) and check every step. It shouldn't be an issue with the plugin itself but project dependencies instead.

Make sure you are using a [valid gradle version](https://stackoverflow.com/questions/62969917/how-do-i-fix-unexpected-element-queries-found-in-manifest/62969918#62969918) as well, since the plugin supports up to Android SDK 30.
