### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by LuisCampos97** [miguelpruivo/flutter_file_picker#492]
Hi!
When I run the command "flutter run" its all fine.
But when I run the command "flutter build apk --split-per-abi", give me an exception:
![imagem](https://user-images.githubusercontent.com/33434500/98717028-6d386600-2384-11eb-866c-b21fdf6d538c.png)

**Comment by VishvaRatnayake** [comment]
hello ! 
i'm getting this error message while building the app.
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.

**Comment by miguelpruivo** [comment]
Hi, this typically happens when projects start back in the days and have some badly migrated modules since `file_picker` supports up to Android 30. Please refer to [this comment](https://github.com/miguelpruivo/flutter_file_picker/issues/481#issuecomment-725099843) to a similar issue with a solution.

**Comment by LuisCampos97** [comment]
It worked for me, with that resolution of that comment.
