### ISSUE TITLE
When running on ios virtual machine, if you choose multiple images, one less image will be returned

### ISSUE THREAD

**Issue by bastYYJ** [miguelpruivo/flutter_file_picker#543]

**Comment by ericmartineau** [comment]
I'm having the case where I'm getting back empty results when using the gallery chooser.  It's as if certain files can't be selected, while others can.  I have another plugin installed in my project to select images and that one seems to work fine. 

I'll try to do some debugging.  I'm not very experienced with Obj-C, only Swift, otherwise I'd submit a PR for it.

**Comment by ericmartineau** [comment]
I think I had the "free" developer account selected under "Signing and Capabilities" within XCode.  This allowed my app to be built, but then it failed (silently).  IMO, this error reporting should be added to the plugin code instead of returning an empty list.

**Comment by jamesdixon** [comment]
@miguelpruivo hope all is well with you!

I can confirm this issue on the iOS simulator....

![image](https://user-images.githubusercontent.com/110114/101940111-38961500-3ba3-11eb-92fc-6bbfca7d4618.png)


In my case, I did the following:

```
final files = await FilePicker.platform.pickFiles(
  type: FileType.image,
  allowMultiple: true,
);

print(files?.count);
```
If I pick the 3 photos, the count displayed is only 2.

On a device, I get the correct number of photos.

That said, not a big deal as long as it works on device but just wanted to confirm this 👍

**Comment by miguelpruivo** [comment]
@jamesdixon hi! I’m find and you?

Are these 3 pictures the ones that came with the simulator? If so, one of each is a HDR picture (the pink flowers) and HDR pictures have an issue with iOS 14 which result in not being picked.
