### ISSUE TITLE
Some extensions are disabled even though they are listed in allowedExtensions

### ISSUE THREAD

**Issue by simone40love** [miguelpruivo/flutter_file_picker#571]
See picture. vtt and srt files are disabled. They should be enabled.
  
void _openFileExplorer() async {
    setState(() => _loadingPath = true);
    try {
      _paths = (await FilePicker.platform.pickFiles(
              allowCompression: false,
              type: FileType.custom,
              allowMultiple: _multiPick,
              allowedExtensions: ['txt', 'vtt', 'lrc', 'smi', 'ssa', 'ass', 'sub', 'srt', 'sbv']))
          ?.files;
    } on PlatformException catch (e) {
      print('Unsupported operation' + e.toString());
    } catch (ex) {
      print(ex);
    }
    if (!mounted) return;
    setState(() {
      _loadingPath = false;
      _fileName = _paths != null ? _paths.map((e) => e.name).toString() : '...';
    });
  }

![Screenshot_20210103-143124_Files](https://user-images.githubusercontent.com/16455677/103487058-7831d480-4dd0-11eb-85d9-132933df59aa.jpg)

**Comment by miguelpruivo** [comment]
@simone40love that’s one of the issues that is described on the troubleshooting. Unfortunately that happens because those extensions can’t be mapped to a valid URI/MIME type.

You’ll have to use `FileType.any` allowing all files to be picked and check the extensions on your end.

I’m sorry for any inconvenience.

**Comment by GULERTOLGA** [comment]
Even though I use FileType.any, I cannot select files with the extension kml. Platform IOS.

**Comment by miguelpruivo** [comment]
@GULERTOLGA that’s odd. Can you provide a sample with a kml file? Thank you!

**Comment by magnuswikhog** [comment]
This threw me off as well, since there is no mention of it in the [API documentation](https://github.com/miguelpruivo/flutter_file_picker/wiki/API) or the in-code documentation for `pickFiles()`. Only found it mentioned in [the FAQ](https://github.com/miguelpruivo/flutter_file_picker/wiki/FAQ).

In my case I was trying to filter `.gpx` files. Perhaps this limitation of MIME type mapping should be mentioned in more places where `allowedExtensions` is described.
