### ISSUE TITLE
Integration with Flutter's file_selector for native desktop support

### ISSUE THREAD

**Issue by marchellodev** [miguelpruivo/flutter_file_picker#630]
Hey, is it possible to integrate this package with [file_selector](https://pub.dev/packages/file_selector) ([file_selector_windows](https://pub.dev/packages/file_selector_windows), [file_selector_linux](https://pub.dev/packages/file_selector_linux), [file_selector_macos](https://pub.dev/packages/file_selector_macos)), so that it will work with desktop operating systems in a native way?

Thanks!

**Comment by miguelpruivo** [comment]
Could be interesting. @stuartmorgan what do you think?

**Comment by stuartmorgan** [comment]
I don't see why it wouldn't possible. There are a lot of different things that could look like, depending on your goal:
1. Make a new meta-package using both (see `file_picker_cross`, which AFAICT is exactly that, but with `file_chooser`, whose code became the `file_selector` implementations).
2. Make your plugin depend on `file_selector` or `file_selector_platform_interface` and use it to implement desktop support as part of this package.
3. Make an adapter package that implements `file_selector_platform_interface`'s API using this plugin, which developers could use an an unendorsed implementation to add mobile support to `file_selector` in their projects.
4. Contribute this plugin's mobile implementations to flutter/plugins as endorsed mobile implementations, and maintain them there going forward, discontinuing this plugin.

1 or 3 could be done by anyone, 2 or 4 depend entirely on your interest in either of those approaches. (If you federated this plugin, the reverse of option 3 would also become possible.)

**Comment by miguelpruivo** [comment]
@stuartmorgan thank you for the input.

Previously I used the interface approach to make it more modular and platform independent, however, since most of the API would require an update anyway when a new feature was added, I found it quite hard to maintain alone and some users wanted to use the app on both web + IO which would result in having to import the 2 packages and sometimes conflict with one on another.

Right now, as it is, it's cross compatible with all platforms (desktop being used only by flutter go) but it would be great to add native desktop support as well. I'll have to think about it.

**Comment by stuartmorgan** [comment]
> and some users wanted to use the app on both web + IO which would result in having to import the 2 packages and sometimes conflict with one on another.

FWIW that just sounds like an implementation bug in one or both of the packages; there's no reason web and non-web implementations of a plugin can't coexist, regardless of federation. (Not too suggest that you should use the federated structure if you don't want to, just that that shouldn't be a reason not to use it.)

> Right now, as it is, it's cross compatible with all platforms (desktop being used only by flutter go)

This is an odd way to describe the current situation; go-flutter-desktop isn't just an add-on someone wanting to use this plugin can adopt, it's a *completely* different implementation of the embedding. Switching would mean using an embedding implementation with different features, capabilities, and bugs. It also means using completely different tooling on desktop than on mobile and web. And giving up every other plugin implementation they are using, and hoping those same plugins have go-flutter-desktop implementations. In short it's *very* unlikely that someone using the official desktop support for Flutter would switch to that embedding just to use this plugin. (This is not a knock against go-flutter-desktop; it's a very interesting project. It's just not trivially interchangeable with the official desktop support from a user perspective. All the same arguments would apply for someone using go-flutter-desktop and wanting to use a plugin that supported the official desktop embeddings but not go-flutter-desktop)

I would suggest thinking of it this way: you currently support Flutter for mobile and web, and you also support people who are using go-flutter-desktop. The latter is great for people already using go-flutter-desktop, but basically irrelevant to people who are currently using Flutter's official desktop support.

**Comment by miguelpruivo** [comment]
That's correct @stuartmorgan. It will probably make sense to add native support as well but it would be great to make it through file_selector since it would cut the time to integrate for all 3 platforms, after all, it's already implemented anyway.

>FWIW that just sounds like an implementation bug in one or both of the packages; there's no reason web and non-web implementations of a plugin can't coexist, regardless of federation. (Not too suggest that you should use the federated structure if you don't want to, just that that shouldn't be a reason not to use it.)

I don't really recall what the issue was, but I remember having something related to the fact of some people requiring the `File` object to be used on their cross-platform project (web and IO) and there is actually a `html.File` and `io.File` object which need to be resolved at compile time to one or another. Of course they could always stub as workaround but could be trickier for some.

**Comment by stuartmorgan** [comment]
Ah, `file_selector` uses https://pub.dev/packages/cross_file to address that issue. I'm not sure why it would be specific to federation though.

**Comment by jgoyvaerts** [comment]
Hi, what's the latest recommended approach? I noticed there's still no single plugin which combines android/ios/web/windows/macos file selector in one package. 

Is this still on the roadmap for this plugin?

**Comment by marchellodev** [comment]
@jgoyvaerts flutter_file_picker does not seem to conflict with file_selector in any way. So just importing both and using one or the other depending on the platform seems to work fine :)

**Comment by miguelpruivo** [comment]
Closing in favor of #271 which is almost done — all desktop platforms will be supported when the feature is merged.

**Comment by stuartmorgan** [comment]
Note that the implementations described in the other issue are showing UI by running stand-alone scripts that aren't associated with the actual application, so will be have non-trivial (and unsolvable) UX issues, as well as being significantly more resource-intensive (spawning an entirely new process just to show a single dialog).

**Comment by miguelpruivo** [comment]
@stuartmorgan got it. But as of now I'd say that is better than nothing, since allow devs to have a seamless experience across all platforms — since I was the only maintainer of this plugin and due to its high popularity, it's hard for me to keep track of all issues on time, specially those requiring big refactors.

If you are interested in adding native support for desktop (without ffi) it would be great, I'd be happy to merge it.

**Comment by stuartmorgan** [comment]
> If you are interested in adding native support for desktop (without ffi)

That's `file_selector`, which already exists; using that is the issue you just closed in favor of using this (less correct) implementation.

**Comment by miguelpruivo** [comment]
@stuartmorgan yes, got your point. That’s correct. Only just because the other solution were already implemented by the time of writing and would be better than nothing. I found that some users could find it handy and I don’t have yet time to implement it using file selector.

I’ll reopen this nevertheless.
