### ISSUE TITLE
Version Solving Issue

### ISSUE THREAD

**Issue by NaingMyoThawNMYT** [miguelpruivo/flutter_file_picker#646]
"**file_picker: ^3.0.0**" and "**flutter_local_notifications: ^4.0.1+2**" cannot use at the same project.
Please can you solve that issue **ASAP**?

Thanks a lot!

**Comment by miguelpruivo** [comment]
@NaingMyoThawNMYT I’m sorry to inform you that this isn’t actually an issue with this plugin but instead to the local notifications.

Turns out that file_picker published its null safety version following the Flutter 2.0 release whereas local_notifications didn’t. You may want to use their 5.0.0-nullsafety version in the meantime or open a issue on its repo.

Thank you.

**Comment by NaingMyoThawNMYT** [comment]
Thank you for your quick response and information.

Keep up the good work!
