### ISSUE TITLE
Feature Suggestion: Timeout feature when file-picker UI is open (security consideration)

### ISSUE THREAD

**Issue by CellCS** [miguelpruivo/flutter_file_picker#660]
Whether there is one timeout param for File picker function. 
This is based on security consideration that Apps auto-logout after there are no user's clicks/activities for a defined time. 

If File-picker could add timeout param for await function, 
like FilePickerResult result = await FilePicker.platform.pickFiles(**timer = 1000**);

Cheers

**Comment by miguelpruivo** [comment]
Hi, thank you for your suggestion.

Unfortunately that shouldn’t be reliable since the user can launch multiple nested activities (or views in iOS) when using the native picker. It’s just not a good practice to “force” close it in a middle of an action and it probably can’t be done because some of the pickings depend upon a 3rd party library that would also need to support the timeout properly.

Because of this, I suggest that you should consider another approach to your app to ensure the user is properly logged out.

Nevertheless, thank you for your suggestion.
