### ISSUE TITLE
Make path, name, bytes and size in PlatformFile nullable or explain in documentation what null means

### ISSUE THREAD

**Issue by ChristianKleineidam** [miguelpruivo/flutter_file_picker#699]
When looking at PlatformFile it's unclear to me why path, name, bytes and size are nullable. It would be great if they would either be turned into non-nullable variables or the documentation would specify what it means when they are null.

**Comment by miguelpruivo** [comment]
- Path is only nullable because of the web, since it doesn’t work with paths;
- Bytes will only be available on web (by default) or if you set `withData` to `true`;
- Name and size shouldn’t actually be null, I believe that there can be an improvement here;

Nevertheless, some of these things can be understood by looking at the docs, but I agree with you.

**Comment by JulianBissekkou** [comment]
This documentation should be part of the code. Would be nice if you could add this to the code in the next release. 

I searched the issues to find out why the path was null (thinking it was a bug).

Thanks! ☺️

**Comment by miguelpruivo** [comment]
@JulianBissekkou you are right. I'll definitely add it.

**Comment by miguelpruivo** [comment]
Added with 3.0.2. 🎉 

Thank you!
