### ISSUE TITLE
Issue when running plugin on multiple platforms

### ISSUE THREAD

**Issue by dancb10** [miguelpruivo/flutter_file_picker#701]
Seems like the plugin behaves different for each platform.
On Android if you use the FileType.any or FileType.media will open basically the same window. When using FileType.media  you are redirected to the gallery window where you can only select ONE image even if you have the allowMultiple: true, parameter set to true. When using FileType.any you can navigate to the gallery folder and select multiple images

On IOS if you use FileType.any or FileType.media will open different apps. The FileType any will only allow you to pick files but you can't see the gallery. The FileType.media opens up the gallery and only with this you can pick images and movies from gallery

**Comment by miguelpruivo** [comment]
Hi. Yes, that’s documented with the wiki. That’s how iOS works. You can’t access both files app and gallery at the same time, it’s not allowed with native pickers, hence the reason why you can see the gallery with image, video and media types but not with the others. Also, filtering extensions only works on the files app.

Regarding Android, I believe that that is due to a recent modification introduced in 3.0.1. Check the version 3.0.0 and see if it suits your needs. I might have to revert it if so.

Thank you.
