### ISSUE TITLE
Add prerequisites to documentation

### ISSUE THREAD

**Issue by barbalex** [miguelpruivo/flutter_file_picker#706]
Documetation of usage shows:

```dart
FilePickerResult result = await FilePicker.platform.pickFiles();

if(result != null) {
   File file = File(result.files.single.path);
} else {
   // User canceled the picker
}
```

Being new to flutter and dart, I could not get this to run. Because it seems you need to import `dart:io` to be able to use the File class.

I suggest adding this prerequisite to the docs. It is not a good experience when the first and most simple example in the docs does not work as shown.

**Comment by miguelpruivo** [comment]
Hi @barbalex, turns out this hasn't been ever an issue because usually the IDEs immediately suggest an import for the given classes and it could potentially add noise to the docs (ie., imagine if the snippet had a lot of imports?).

Nevertheless, thank you for the suggestion, I might add it since it's only 2 imports for the given example (the picker and dart:io).
