### ISSUE TITLE
Why it takes 2 seconds.

### ISSUE THREAD

**Issue by Morris-Mao** [miguelpruivo/flutter_file_picker#713]
**Describe the bug**
It seams that withData = false is not work on Android. It takes 2 seconds  from status picking to done when i pick a 500MB files. Does it read the file in memory??

**Platform**
- [] Android

**Platform OS version**
Android 10

**How are you picking?**
```
 FilePickerResult result =
                await FilePicker.platform.pickFiles(
                    allowMultiple: true,
                  withData: false,
                  onFileLoading: (status) {
                      print("pick $status");  // It takes 2 seconds  from status picking to done when i pick a 400MB files
                  }
                );
```
**Details to reproduce the issue**
Provide all the details to reproduce the issue.

**Error Log**
I print the log in the callback of  onFileLoading.  The time takes 2 seconds.
```
2021-05-15 15:28:39.127 3918-3991/xxx I/flutter: pick FilePickerStatus.picking
2021-05-15 15:28:41.121 3918-3991/xxxx I/flutter: pick FilePickerStatus.done
```

**Screenshots and/or video**
If applicable, add screenshots or video to help explain your problem.

**Flutter Version details**
 Flutter (Channel stable, 2.0.2, on Mac OS X 10.15.7 19H2 darwin-x64, locale
    zh-Hans-CN)

**Additional context**

**Comment by miguelpruivo** [comment]
Hi, it caches the file (it has to) due to scoped storage since Android 30. If we didn't cache the files, we can't have an absolute valid path and we have a native URI only to manage the file, which can't be used on the Flutter side.

You can read more about it [here](https://github.com/miguelpruivo/flutter_file_picker/wiki/FAQ) in the first question.

Sorry for any inconvenience.
