### ISSUE TITLE
Duration of video/audio files

### ISSUE THREAD

**Issue by Zelfapp** [miguelpruivo/flutter_file_picker#758]
Would be great if the FileType is video/audio if we could get access to more meta for these file types. At the minimum, would be great to be able to get the `duration`, but also `height`, `width`, `orientation`, etc.

**Comment by miguelpruivo** [comment]
Hi, thank you for the suggestion @Zelfapp but this plugin is mean to act only as a picker. I’d like to keep things simple to not confuse/introduce more complexity to the API, specially because that would only work for some kind of files.

By keeping plugins modular it’s easier to maintain and you can easily combo with plugins such as [flutter_video_info](https://pub.dev/packages/flutter_video_info) to get what you need.

Because of this, this is a no-op for now.
