### ISSUE TITLE
file picker didn't return the absolute path

### ISSUE THREAD

**Issue by InDividjualCreations** [miguelpruivo/flutter_file_picker#774]
I Want to get a file path that user selects. i used file picker for this operation. it's work great. but it' only return that path cache location like this "/data/user/0/com.example.id_safe/cache/file_picker/icon.png". but i want to get "/storage/0/emulated/filename" like this. what can i do? please help me.

**Comment by mlepage** [comment]
I have been learning Flutter for a few weeks now and am experiencing the same in my Android app. From what I can tell, you get a local cache instead of the originally picked file, because some cases (cloud) and iOS and also maybe Android permissions mean it's not possible.

However in my app, I'd still like to get the original path for cases that are supported (e.g. downloaded files on Android) so I can offer extra functionality. Basically, I want to allow the user to pick one downloaded file from a set of related download files, and have my app automatically find the sibling related files (if they exist), without requiring the user to pick them all.

I'd also like to periodically (e.g. once per app launch) check the original location for new files (so they can be added), or removed files (so my app's view of them can be removed).

It seems I cannot do this without having the original (non-cached) paths.

**Comment by InDividjualCreations** [comment]
> I have been learning Flutter for a few weeks now and am experiencing the same in my Android app. From what I can tell, you get a local cache instead of the originally picked file, because some cases (cloud) and iOS and also maybe Android permissions mean it's not possible.
> 
> However in my app, I'd still like to get the original path for cases that are supported (e.g. downloaded files on Android) so I can offer extra functionality. Basically, I want to allow the user to pick one downloaded file from a set of related download files, and have my app automatically find the sibling related files (if they exist), without requiring the user to pick them all.
> 
> I'd also like to periodically (e.g. once per app launch) check the original location for new files (so they can be added), or removed files (so my app's view of them can be removed).
> 
> It seems I cannot do this without having the original (non-cached) paths. I'd be happy to do this with non-cloud files on Android only, because even if I support an iOS version of my app, I just would not have the ability to interact with downloaded files as a feature.

I have an another plan. that only access from a specific location like Documents/myFolder. Is there any way to do it in file picker?

**Comment by miguelpruivo** [comment]
Dup of #776.

Please, check the answer and read the [FAQ](https://github.com/miguelpruivo/flutter_file_picker/wiki/FAQ). You can't access the original paths, that's a platform limitation on both iOS and Android (since SDK 30).

**Comment by Jakuzeisme** [comment]
@InDividjualCreations @mlepage 
Find any work around?
