### ISSUE TITLE
Cached file names not unique?

### ISSUE THREAD

**Issue by mlepage** [miguelpruivo/flutter_file_picker#777]
This presents a problem if the user picks items with the same name in different directories. E.g. if I pick 'icon.png' and then later pick another 'icon.png.' Or if I have several directories, each with files named 'epN.mp3' where N is a number, then I play one directory's ep1.mp3, I cannot subsequently play another (i.e. it's still ep1.mp3 from the first directory, not ep1.mp3 from the subsequent directory).

The documentation doesn't say how cached file names are generated. It does mention that it's smart enough not to re-cache if the same file is picked. But it doesn't say how it treats the same file name in different directories. Obviously if it's determining file "sameness" by name, this isn't going to work for different files in different directories, that may happen to have the same name. (E.g. 'notes.txt')

Tangentially, I'd also like to know how long cached files stay around. E.g. if I pick 20 audio files to play over time, will the 20th still be cached when I finally get to playing it? How could you use the file picker to build a "playlist" of local audio files to play? (A lot of the documented use cases seem to revolve around consuming/processing the picked files immediately, but not all apps function that way...)

**Comment by miguelpruivo** [comment]
Hi!

Cached files work a bit differently on each platform, but the base idea is the same — both are handled by the OS since they are cached on their own temp directories. If you look at the platform documentation you can see that there's no reliable way to ensure that the files on the tmp directories will be there since the OS can pure when needed. What I suggest is that the dev should take care of the picked files and move to another directory (ie., app's documents directory) so he can actually manage to suit the app requirements — see the picker just as a way to pick the files, what will happen next is up to you.

Regarding the repeated files question, yes, it's based on the file name on Android. On iOS it's always picked anyway, the cached is handled internally.

**Comment by Malik056** [comment]
I am having the problem, if I pick a file and then pick the same file but before picking the file again update the file a little, it return the old version of the file.

**Comment by Malik056** [comment]
I tried `clearTemporaryFiles` function but no luck

**Comment by kevinbader** [comment]
Is there a follow-up to this, or at least a workaround? @miguelpruivo  Reading the wrong file when selecting another file with the same name means that picking files is essentially broken, wouldn't you agree?

> What I suggest is that the dev should take care of the picked files and move to another directory

Do you mean the application should delete the cached file? How to know whether this is safe, and not the real file on different platforms / in the future?
