### ISSUE TITLE
[suggestion] editing and saving same picked file

### ISSUE THREAD

**Issue by premingiet** [miguelpruivo/flutter_file_picker#790]
Here is the issue i am currently facing. Its a very simple task of picking a txt file and then i need to edit few changes in that txt file and i wish to save the changes to the same file. With current flutter_file_picker package, i am unable to do that, because i never get the absolute path of the file, all i get is cached path of file. I am using android by the way and i think this simple task should be supported. Because if i am making a text editor application, then how will i save changes to that same file i picked earlier ? please help regarding this issue.

**Comment by miguelpruivo** [comment]
Hi, this is not actually an "easy task" nor it's possible, since SDK 30. Android API "forces" you to either use native URI (which makes it impossible for CRUD operations on Dart side) or make a cached copy, you can't directly manipulate the original file, hence the reason you don't have the path — read more about it [here](https://github.com/miguelpruivo/flutter_file_picker/wiki/FAQ).

What I can suggest you is to as soon as the user picks the files, move it to your own app's permanent storage and use it from there. This also makes it reliable to recover the original file if the user for some reason wants.
