### ISSUE TITLE
How to pick picture only from Camera?

### ISSUE THREAD

**Issue by satriantorobimo** [miguelpruivo/flutter_file_picker#793]
Hi, i want to ask how to pick picture only from Camera?

Thank You

**Comment by miguelpruivo** [comment]
Hi, you need to use the `[image_picker](https://pub.dev/packages/image_picker)` plugin. On early versions of this plugin there was such feature, but then I was asked to remove it because it could make the plugin heavier and also ask for permissions that the devs wouldn't actually use. Also, since you have a plugin that you can easily combo with this one, it is better for maintainability.

Sorry for any inconvenience.

**Comment by satriantorobimo** [comment]
Ok thank you, my purpose it for flutter web. So i want to upload picture only just using camera instead of pick from file or library.
