### ISSUE TITLE
Please add a "save as" / "new file" dialog

### ISSUE THREAD

**Issue by jonmountjoy** [miguelpruivo/flutter_file_picker#799]
Hello!

Would it be possible to extend the native dialogs to handle the "Save As" action.  It's similar to the directory selection that's already there, but provides a text field for the file name, as shown below for MacOS:

![image](https://user-images.githubusercontent.com/545244/129487756-faeadee8-3581-4310-b6ea-02c09627e898.png)

This could be an entirely new API method I guess, or perhaps extend `FileType` with a `save`option, and allow something like:

```
FilePickerResult? result = await FilePicker.platform.pickFiles(type: FileType.save);
```

Thanks!

**Comment by miguelpruivo** [comment]
@philenius could it be done?

**Comment by philenius** [comment]
@miguelpruivo yes, I already have a working implementation for a save-as dialog on Windows, Linux, and macOS. I could easily integrate it.

**Comment by miguelpruivo** [comment]
I believe that picking directories is enough and serves the same purpose on mobile.

**Comment by philenius** [comment]
@miguelpruivo could you please resend the invitation for your repository so that I can contribute? Sorry to bother you again. The original invitation has expired because I was on vacation in the meantime. Thank you.

**Concerning this issue:**
Because you're not planning to implement a separate save-file-dialog for Android and iOS I would suggest two different approaches:

1. @jonmountjoy proposed to add an additional `FileType`, e.g. `FileType.save`. I don't think that this is a good idea because the save-file-dialog allows to set a file type filter. If we were to use `FileType.save` for showing a save-file-dialog, then we couldn't set a file type filter at the same time. The following screenshot shows the save-file-dialog on Ubuntu where the file type filter is set to filter for image files:
![image](https://user-images.githubusercontent.com/9049899/132262648-5a338a3e-e09e-4568-90ca-7a18cee6abce.png)
  

2. I would prefer to add an additional, boolean parameter to `FilePicker.platform.pickFiles()`, e.g. `saveFileDialog`. This parameter would only have an effect on desktop platforms (no effect on iOS/Android).

Unfortunately, we'll need one more additional parameter to set the default file name (the save-file-dialog includes a title, a file type filter, and a default file name).
![image](https://user-images.githubusercontent.com/9049899/132262477-2f51ec3b-531d-4650-b4fb-f889d2d7c459.png)
![image](https://user-images.githubusercontent.com/9049899/132262518-f4c4e143-94eb-45d7-9a2c-f69f618c37ad.png)


So, the final API could look like this:
```dart
Future<FilePickerResult?> pickFiles({
    String? dialogTitle,
    FileType type = FileType.any,
    List<String>? allowedExtensions,
    Function(FilePickerStatus)? onFileLoading,
    bool allowCompression = true,
    bool allowMultiple = false,
    bool withData = false,
    bool withReadStream = false,
    // NEW:
    bool saveFileDialog = false,
    // ALSO NEW:
    String? defaultFileName,
  }) async { ... }
```

Knowing that we'll need two additional parameters, do you still want to integrate the save-file-dialog in the existing function `pickFiles()`?

**Comment by miguelpruivo** [comment]
@philenius I'm afraid this could confuse IO users with even more parameters, however, if it's handy for some, I don't see a reason why we shouldn't add it as well.

I'm trying to understand what is this feature about — it's just to pick a location without picking the files? If so, the best approach would be adding a desktop implementation only for saving the files with a new method, something like `FilePicker.instance.saveAs({String fileName})`. That implementation would throw an `UnimplementedError` in the other platforms and would work only in desktop. Looks like the most reliable way to me. What do you think?

**Comment by philenius** [comment]
@miguelpruivo, exactly, that was my thought, too. Too many parameters can become confusing.

You go the idea right. A save-file dialog allows the user to select an **output file**. In the example of a tool for creating PDF files: the user can select the path and name of the output file (either an existing file or a new file) to which the program will write/export the PDF file. The return value of the save-file dialog is only the path to the file.

I like your idea of providing
```dart
FilePicker.instance.saveAs({
    String? dialogTitle,
    String? fileName,
    FileType type = FileType.any,
    List<String>? allowedExtensions
})
```
for desktop platforms and throwing an exception on mobile platforms. If you add me as a contributor, then I'd love to do the implementation.

**Comment by miguelpruivo** [comment]
@philenius are the file type and extensions required for that as well? Sure I’ll add you right away.

**Comment by philenius** [comment]
@miguelpruivo: the decision is up to you whether file type and extensions can be configured, too. At least it has an effect on Windows and Linux:

1.Allow any file types: `test.dart` is shown

| Ubuntu        | Windows |
| ------------- |-----------|
| ![Ubuntu](https://user-images.githubusercontent.com/9049899/132771902-d09aa658-93ee-4ca5-8d2c-a74cd7b00782.png) | ![Windows](https://user-images.githubusercontent.com/9049899/132775330-ef0f2fd7-6289-4b07-89a3-c4c2cec3d885.png) |

2. Allow only image files: `test.dart` is hidden 

| Ubuntu        | Windows |
| ------------- |-----------|
| ![image](https://user-images.githubusercontent.com/9049899/132772007-23c67568-25ae-4eee-8f78-37de045f9a15.png) | ![Untitled2](https://user-images.githubusercontent.com/9049899/132775378-271954ce-c418-4a1c-919a-6618433a3659.png) |

On macOS, I wasn't able to filter by file type. Although, the dialog in @jonmountjoy 's screenshot (first message in this issue) shows a dropdown for setting the allowed file types.

**Comment by jonmountjoy** [comment]
I much prefer the proposed direction of creating a new API method as you're doing in https://github.com/miguelpruivo/flutter_file_picker/issues/799#issuecomment-915580609 , than my original proposal.

👍

**Comment by miguelpruivo** [comment]
@philenius already invited you. Yes, looks like a good approach, you're good to go.
