### ISSUE TITLE
Example app is not asking for permission for the Photo library. IOS

### ISSUE THREAD

**Issue by jinthislife** [miguelpruivo/flutter_file_picker#806]
First, thanks for your hard work on this handy plugin!

**Describe the bug**
I first found this issue in my project using flutter_file_picker. I wanted to make sure the example app has the same issue, and it is reproduced easily.

**Platform**
- [] Android
- [v] iOS
- [] Web
- [] Desktop (Go)

**Platform OS version**
What version did it happen?
iPhone 7 Plus iOS 14.6
iPhone 12 Pro Max 14.2
iPhone 12 Pro Max 14.5

**Details to reproduce the issue**
I just first runned the example of flutter_file_picker. 
Select FROM IMAGE from the drop-down.
Tap Open file picker button.
==> Native picker is open without being asked for the permission. 

**Flutter Version details**
2.2.2

**Additional context**

**Comment by ModernaVaccine** [comment]
Same issue here. file_picker is completely ignoring iOS permission settings. Opens photo album even when I disable the permission manually with permission_handler package.

**Comment by miguelpruivo** [comment]
iOS has very restrict security measures, there's no way the plugin can go around the allowed permissions (otherwise devs could bypass and the user would think that he/she was safe).

If the plugin can access the images, videos etc. it's because is allowed to, probably the permission_handler is not working properly. Try toggling off all the permissions in the privacy settings of the iOS and you'll see you won't be able to open the gallery.

**Comment by ModernaVaccine** [comment]
Update:
Just to clear thing up.
Asking for photo permission is not necessary, if you are using the default IPhone album browser. This plugin invokes the native album browser, and the user is in control the whole time about which image he want to give to the app.
If the app wanted to access the photos by itself, then asking for permissions would be necessary.

**Comment by miguelpruivo** [comment]
That's correct @ModernaVaccine.
