### ISSUE TITLE
When using directory picker in Kde on linux shows saving dialog instead

### ISSUE THREAD

**Issue by prateekmedia** [miguelpruivo/flutter_file_picker#839]
**Describe the bug**
When using directory picker in Kde on linux it shows saving file dialog instead. 
**Note**: KDE uses dolphin instead of nautilus for file explorer.

**Platform**
- [x] Desktop (Go)

**Platform OS version**
Any KDE linux distro

**How are you picking?**
```dart
await FilePicker.platform.getDirectoryPath(dialogTitle: 'Choose Download Folder');
```

**Screenshots and/or video**
![](https://user-images.githubusercontent.com/60552903/135256668-7094528f-5f87-4e7a-abb5-2b0a1a290972.png)

**Flutter Version details**
2.6 beta

**Additional Context**
Taken from https://github.com/prateekmedia/appimagepool/issues/7

**Comment by philenius** [comment]
Hi @prateekmedia, I took the effort to install Mageia 8 with KDE Plasma in a virtual machine. I had to manually install `zenity` because it wasn't preinstalled (`zenity` is part of GNOME) (internally, this Dart package uses `qarma` or `zenity` depending on what is available to open the file-picker / dir-picker dialog).
Then, I downloaded your app _AppImagePool_ and navigated to the settings to change the download folder. As expected, the dialog for picking a directory is shown (in contrast to the screenshot by @philippe1973 which shows the save-as/save-file dialog).

![image](https://user-images.githubusercontent.com/9049899/135339286-8d8d94c0-220a-4d88-b12e-8cfcfa453a76.png)

Now, I am wondering why @philippe1973 and I get to see different dialogs? What's the difference?

**Comment by prateekmedia** [comment]
Thanks @philenius for your time, actually you need to install the flatpak version listed on the readme.

**Comment by prateekmedia** [comment]
I have updated flatpak runtime to use gnome in hope that this is a bug when gtk is not available so it uses native file manager which causes the bug.

**Comment by philenius** [comment]
hey @prateekmedia, I just wanted to let you know that, thanks to a contributor, we now support KDialog which comes preinstalled with KDE!
