### ISSUE TITLE
Lint found errors in the project; aborting build.

### ISSUE THREAD

**Issue by Simpler1** [miguelpruivo/flutter_file_picker#851]
**Platform**
- [x] Android
- [] iOS
- [] Web
- [] Desktop (Go)

```
$ android/gradlew clean
$ android/gradlew build

> Task :file_picker:lint FAILED
Ran lint on variant debug: 9 issues found
Ran lint on variant release: 9 issues found
Ran lint on variant profile: 9 issues found
Wrote HTML report to file:///home/kevin/git_projects/flutter_assets/build/file_picker/reports/lint-results.html
Wrote XML report to file:///home/kevin/git_projects/flutter_assets/build/file_picker/reports/lint-results.xml
w: Detected multiple Kotlin daemon sessions at ../build/kotlin/sessions

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':file_picker:lint'.
> Lint found errors in the project; aborting build.
  
  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...
  Errors found:
  
  /home/user1/.pub-cache/hosted/pub.dartlang.org/file_picker-4.1.4/android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java:188: Error: Call requires API level 19 (current min is 16): android.provider.DocumentsContract#getDocumentId [NewApi]
                  String docId = DocumentsContract.getDocumentId(treeUri);
                                                   ~~~~~~~~~~~~~
  /home/user1/.pub-cache/hosted/pub.dartlang.org/file_picker-4.1.4/android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java:66: Error: Value must be ≥ 0 [Range]
                          result = cursor.getString(cursor.getColumnIndex(OpenableColumns.DISPLAY_NAME));
                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by Simpler1** [comment]
The first error can be fixed by editing 
`~/.pub-cache/hosted/pub.dartlang.org/file_picker-4.1.4/android/build.gradle`
and changing
`minSdkVersion 16`
to
`minSdkVersion 19`

**Comment by AngeloAvv** [comment]
@miguelpruivo any updates? This library is breaking my CI builds due to lint failure. I think the android linter can't understand the [previously defined](https://github.com/miguelpruivo/flutter_file_picker/blob/13bc9b478eec34651a2e915398b9905ea3ab7ce5/android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java#L187) check regarding the android version defined before [this row](https://github.com/miguelpruivo/flutter_file_picker/blob/13bc9b478eec34651a2e915398b9905ea3ab7ce5/android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java#L189)

Even if you targeted your project minSdkVersion to 19 or above, the linter will keep failing because the internal lint task of your library uses the minSdkVersion of the library, which is 16.

You can reproduce it by creating a new flutter project with this very dependency and then run the android gradle task `lintDebug` or `lintRelease`
