### ISSUE TITLE
default or custom directory on pickFiles?

### ISSUE THREAD

**Issue by lastmeta** [miguelpruivo/flutter_file_picker#859]
I can't find any documentation about being able to specify the directory that the dialog box opens to by default. is this a feature? if so, how can it be done? I would, of course expect to be able to say:
`FilePicker.platform.pickFiles(directory: path);`

I don't know much about android or IOs directory structures, is this kind of thing prohibited by the OS?

**Comment by kion** [comment]
I'd also really like to see this feature implemented.

I actually forked the repo and tried to look into the implementation myself and was able to confirm it's possible to implement for Linux/Zenity at least.

E.g.:

`zenity --file-selection --filename=/home`

would open the file chooser dialog with the "/" location as the default and the "/home" folder selected.

`zenity --file-selection --filename=/home/`

(notice the trailing slash) would open the file chooser dialog with the "/home" as the default location.

I played with the source code and tried to tweak Zenity specific implementation (i.e. for GTK+ only) and was able to get it working, but then I realized that Qarma implementation (which I don't have available locally) would be required as well (even though taking into account Qarma is a clone of Zenity for Qt, I'd assume it should be just as straightforward as it was for Zenity). And then, of course, I'd need to implement same stuff for MacOS and Windows too, so that's where I stopped as I don't have access to all the corresponding environments to test the implementation on (not to mention I'd need to figure out all the platform specific implementation details too... which I believe I actually did for MacOS, but Windows specific code looked so horribly unfamiliar and counter intuitive to me that it basically killed my enthusiasm and I decided to gave up :))).

I hope we'll see this feature implemented at some point though.

In either case, keep up the great job on the plugin (I migrated from another one that wasn't using the native file chooser dialog and I love this implementation way more!).

**Comment by philenius** [comment]
I came up with an implementation and committed it to the branch `feature/initial-directory`. I changed the signature of **all three methods** (`pickFiles()`, `getDirectoryPath()`, and `saveFile()`) to include an additional parameter `initialDirectory`. Example code:

```dart
await FilePicker.platform.pickFiles(
  initialDirectory: '/home/johnDoe/workspace',
);
await FilePicker.platform.getDirectoryPath(
  initialDirectory: '/home/johnDoe/workspace',
);
await FilePicker.platform.saveFile(
  initialDirectory: '/home/johnDoe/workspace',
);
```

Thank you, @kion, for figuring out the trick with `--filename=/absolute/path/to/initial/dir`. I was able to successfully implement and test the Linux and macOS implementations. Only the Windows implementation does not work completely:

* **Linux:**
   - [x] `pickFiles()`
   - [x] `getDirectoryPath()`
   - [x] `saveFile()`
* **macOS:**
   - [x] `pickFiles()`
   - [x] `getDirectoryPath()`
   - [x] `saveFile()`
* **Windows:**
   - [x] `pickFiles()`
   - [ ] `getDirectoryPath()` :x: seems like setting the initial directory is not supported when picking a directory
   - [x] `saveFile()`

@HankG it is now on you to provide the missing implementations for iOS and Android :wink:

**Comment by kion** [comment]
Great job @philenius - thanks a lot for spending time on getting this done - it'd really be a great improvement, so let's hope it finds its way to the master branch soon!

**Comment by miguelpruivo** [comment]
@philenius thank you for the effort on this. I remember doing a triage on this a while ago when the feature was first suggested, however, I found some limitations on Android or iOS (I don’t really remember which one).

Nevertheless we can do a research again to take full advantage of such feature, it will come in handy for some.

**Comment by w1th0utnam3** [comment]
If I'm seeing this correctly this feature is blocked because of missing implementations for the mobile platforms? In my opinion it would be fine to merge a desktop only implementation _for now_ and ignore the option on mobile platforms _for now_ (and document it as platform specific behavior) if an implementation is not possible there or is too complex for an initial PR. Because in general it is of course a useful feature to have but I think it's also not a deal breaker if the picker ignores it?

**Comment by kion** [comment]
I agree with @w1th0utnam3 - it would be great to see this one merged in, so that the desktop apps start benefiting from it, even if it's not possible (or is more complex and requires more time) to implement it for the mobile platforms (also, FWIW, I think this feature is much more valuable/important for the desktop apps than it is for the mobile ones anyways).

**Comment by philenius** [comment]
fyi: we just released version 4.4.0 which implements the new parameter `initialDirectory` for all desktop platforms.

**Comment by BernardinD** [comment]
Any update on getting the initialDirectory feature on mobile?

**Comment by imiskolee** [comment]
did someone working on it on mobile device?
