### ISSUE TITLE
Google Play Update Canceled - Acess to all files with using file_picker

### ISSUE THREAD

**Issue by rulila52** [miguelpruivo/flutter_file_picker#864]
I want to release an update for my application where I am using file_picker to select files. My update is being rejected with reference to the following:

```
Issue: Access to device storage not required

The feature you identified does not require unrestricted access to device storage. There are other privacy friendly options for accessing files in shared storage, such as using the system file picker, or, depending on the use case, you can follow the recommendations for receiving data from other apps listed here.

Please update your app so that the feature uses a privacy friendly alternative and remove All Files Access (MANAGE_EXTERNAL_STORAGE) permission.
```

https://support.google.com/googleplay/android-developer/answer/9888170#all-file-access

I checked my app manifest and only found "android.permission.READ_EXTERNAL_STORAGE"  which comes from file_picker. Why is google play rejecting an app with file_picker? Am I doing something wrong?

**Comment by miguelpruivo** [comment]
This probably can be removed from the plugin and allow devs to add on their applications only when required. I'll do it right away.

**Comment by miguelpruivo** [comment]
Fixed with 4.2.2.

**Comment by rulila52** [comment]
I don't think this will solve the problem. file_picker will not work without this line, and if you add it, you get the same thing. I thought that someone might have encountered this problem already. I have a feeling that this mechanism has been altered in android, and it is no longer possible to use the old one, or without publishing the application

**Comment by miguelpruivo** [comment]
Hum I find it odd that you’re the first one encountering this issue though.

**Comment by rulila52** [comment]
Maybe I'm wrong. I just meant that the new version, on the contrary, can break something in other people. this one can be closed

**Comment by MrCsabaToth** [comment]
I know it's hindsight but the error message was about `MANAGE_EXTERNAL_STORAGE`. So some plugin includes that for @rulila52 https://stackoverflow.com/questions/62782648/android-11-scoped-storage-permissions

**Comment by miguelpruivo** [comment]
@MrCsabaToth do you think that there is something that I can do to prevent it at the plugin level?

**Comment by MrCsabaToth** [comment]
@miguelpruivo I don't think you can do anything (if it is not your plugin which brings in the `MANAGE_EXTERNAL_STORAGE`, and that's the case). I believe in @rulila52's case some other lurking plugin / part brought in that particular permission entry.

**Comment by karamatpkid** [comment]
i am also facing same issue. even i have not included (`MANAGE_EXTERNAL_STORAGE`) permission.
<html>
<body>


Issue found: Access to device storage not requiredThe feature you identified does not require unrestricted access to device storage. There are other privacy friendly options for accessing files in shared storage, such as using the system file picker, or, depending on the use case, you can follow the recommendations for receiving data from other apps listed here.Please update your app so that the feature uses a privacy friendly alternative and remove All Files Access (MANAGE_EXTERNAL_STORAGE) permission.
--



</body>
</html>Issue found: Access to device storage not required
The feature you identified does not require unrestricted access to device storage. There are other [privacy friendly options](https://developer.android.com/training/data-storage/use-cases) for accessing files in shared storage, such as using the system file picker, or, depending on the use case, you can follow the recommendations for receiving data from other apps listed [here](https://developer.android.com/training/sharing/receive).

Please update your app so that the feature uses a privacy friendly alternative and remove All Files Access (MANAGE_EXTERNAL_STORAGE) permission.
