### ISSUE TITLE
pickFiles may cause stuck only in macos app

### ISSUE THREAD

**Issue by shukaka** [miguelpruivo/flutter_file_picker#874]
**Describe the bug**
pickFiles may cause stuck only in macos app.

**Platform**
- [x] Desktop (mac m1)

**Platform OS version**
M1 macos bigsur 11.4

**How are you picking?**
```
    await FilePicker.platform.pickFiles(
      dialogTitle: 'Test File Picker',
      allowCompression: false,
      allowedExtensions: ['jpg', 'png'],
    );
```

**Details to reproduce the issue**
[filepickerdemo.zip](https://github.com/miguelpruivo/flutter_file_picker/files/7543160/filepickerdemo.zip)
1. download the demo project, run as macos desktop mode
2. click 'pick file', then cancel or select, repeat this several times, the flutter mac app will stuck

**Screenshots and/or video**
https://user-images.githubusercontent.com/6303933/141891037-2befe287-8bee-4d5a-8109-0edba1528f26.mp4

**Flutter Version details**
Flutter 2.6.0-12.0.pre.654 • channel master • git@github.com:flutter/flutter.git
Framework • revision 3faeb6f738 (7 days ago) • 2021-11-08 22:37:35 -0500
Engine • revision 5fcc59bbc2
Tools • Dart 2.15.0 (build 2.15.0-285.0.dev)

**Comment by philenius** [comment]
@shukaka thank you very much for providing a video and example code.

Unfortunately, I was not able to reproduce your issue. I downloaded your example app and ran it three times. Each time I clicked at least 10 times on the `cancel` button of the file picker dialog. The Flutter app kept responding as it should. ¯\_(ツ)_/¯
The fact that I couldn't reproduce this error might also have something to do with the fact that I don't own a physical macOS device (only virtualized). But, I have one idea:

Could it be that your issue is related to your Flutter version? You are using a non-stable pre-release of Flutter from the master channel (**2.6.0**-12.0.**pre**.654). 
I reinstalled Flutter today and the latest stable version seems to be _v2.5.3_. Please switch to the `stable` channel, rebuild your Flutter app and try again:
```bash
flutter channel stable
flutter upgrade
flutter doctor
cd filepickerdemo/
flutter clean
flutter build
flutter run
```

Please let us know whether the steps above solved your issue. Thanks.

**Comment by jiagengArctuition** [comment]
@philenius thanks! when i switch to flutter stable version, the problem is gone.

**Comment by exitist** [comment]
I can reproduce the exact same behaviour in stable 2.8.1 m1 mac debug mode. But the problem goes away when the plugIn running in release mode

**Comment by RaphaelRevivor** [comment]
I'm getting similar issue (i.e. open the dialog, then cancel, then repeat previous actions; app will soon get stuck) with Save-file / save-as dialog, on Flutter channel stable 2.8.1, m1 mac. My macOS version is 12.0.1.
