### ISSUE TITLE
Feature Request : Give numbering to files while multi-selecting files.

### ISSUE THREAD

**Issue by SatyamKr07** [miguelpruivo/flutter_file_picker#879]
Currently when multi-selecting files, we see blue tick . It would be best if you give numbering to files while multi-selecting files. It will help in ordering multiple files effectively. Thanks :)

**Comment by jamesdixon** [comment]
@SatyamKr07 did you find a way around this?

**Comment by miguelpruivo** [comment]
@jamesdixon im afraid he didn’t (at least with this package). 


I’m also interested in change the ticker, just hadn’t the time yet.

**Comment by jamesdixon** [comment]
@miguelpruivo do you know if this is possible or is it a limitation of the pickers that have been implemented? I noticed that the native picker in the Photos app on iOS has this capability.

**Comment by jamesdixon** [comment]
It looks like the [DKImagePickerController](https://github.com/zhangao0086/DKImagePickerController) lib does support numbering and I saw a related issue here: https://github.com/zhangao0086/DKImagePickerController/issues/251

Not sure if I'm missing something?

Also, no clue if this works on Android since it seems that it can use different pickers.

**Comment by miguelpruivo** [comment]
@jamesdixon hi! Might have to take a look into it. It should be possible.
