### ISSUE TITLE
File Picker not spawning on Linux (Ubuntu 20.04.3 LTS)

### ISSUE THREAD

**Issue by jlnrrg** [miguelpruivo/flutter_file_picker#903]
**Describe the bug**
At first I thought it was just my problem, so I cloned your repo and tried the example folder with linux support enabled:
The picker is not showing up. Attached video for demonstration

**Platform**
- [ ] Android
- [ ] iOS
- [ ] Web
- [x] Desktop (Go)

**Platform OS version**

```bash
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```

**How are you picking?**
I did not modify your example folder, so however it is handled there.

**Details to reproduce the issue**
1. clone the repo
2. navigate to the example folder
3. `flutter config --enable-linux-desktop`
4. `flutter create . --org com.mr.flutter.plugin`
5. debug using the linux desktop

**Error Log**
No errors were found in the debug console

**Screenshots and/or video**

https://user-images.githubusercontent.com/77293597/144243297-115a161e-722a-4756-a674-3243eee295e3.mp4

**Flutter Version details**

```bash
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (7 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4
```

**Comment by philenius** [comment]
Thank you for providing a screen recording, @jlnrrg . I followed your steps, created a fresh copy of the GitHub repository, and ran the example app. On my laptop, everything works as expected :thinking:  Frankly, I'm a little stumped here...

My environment is exactly the same as yours (even the same Ubuntu distribution):
```
[✓] Flutter (Channel stable, 2.5.3, on Ubuntu 20.04.3 LTS)
    • Flutter version 2.5.3 at /home/phil/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (7 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
```

Which version of this `file_picker` do you use? It should be the latest version because you cloned it from GitHub, right?

Internally, the Linux implementation of `file_picker` executes a simple shell command. Ideally, we would call the Linux C++ APIs directly but we lack the expertise to implement this. Therefore, we use one of the CLIs `qarma` or `zenity` (whichever is available) instead. The following command should open a file picker dialog. Can you please check this?
```bash
# zenity should be available on Ubuntu
zenity --file-selection --title "Select a file:"
# alternatively:
qarma --file-selection --title "Select a file:"
```

**Comment by jlnrrg** [comment]
The screenrecording is a given :smile: 

The example project uses:
```yaml
file_picker:
    path: ../
```

and the upper folder is version 4.2.6

`zenity --file-selection --title "Select a file:"`
worked like a charm

`qarma --file-selection --title "Select a file:"`
didn't work, as the command was not found

This is indeed a peculiar problem.
If I can be of further assist, I am willing to do a screen sharing if that is of interest to you.
You can find my contact info in my profile.
(Otherwise this is also fine)

**Comment by jlnrrg** [comment]
I enabled to debug all Exceptions and uncaught Exceptions and the filePicker throws the error:
`_Exception (Exception: Couldn't find the executable qarma in the path.)`
Which is bc `qarma` is not installed on my system.
As noted before this should be the alternative solution, so there might be an error of trying to instantiating it even when it is not used.

**Comment by philenius** [comment]
Thank you for providing all the details, @jlnrrg.

> I enabled to debug all Exceptions and uncaught Exceptions and the filePicker throws the error:
_Exception (Exception: Couldn't find the executable qarma in the path.)
Which is bc qarma is not installed on my system.
As noted before this should be the alternative solution, so there might be an error of trying to instantiating it even when it is not used.

Also, thanks for checking with `All Exceptions` enabled in VS Code. As you said, this exception is expected behavior because we check for _qarma_ first and then use _zenity_ as a backup:

https://github.com/miguelpruivo/flutter_file_picker/blob/9b75f4016e2848aa1b1d14ca1523f0634a5b018d/lib/src/file_picker_linux.dart#L91-L97

Thanks for offering a screen sharing. I might contact you for a screen sharing but honestly I'm too busy writing my master thesis.

**Comment by jlnrrg** [comment]
A totally reasonable excuse :smile:.

Is `qarma` chosen as the default over `zenity` by design?

If not I could offer a PR to first check for existence, to reduce your workload a little :+1: .

**Comment by philenius** [comment]
@jlnrrg , thank you for your understanding.

There is no particular reason why we check `qarma` first followed by `zenity` other than that the original implementation in Go (https://github.com/gen2brain/dlgs/blob/master/dlgs_linux.go) does it the same way. I'd be fine with you creating a PR to switch the order so that `zenity` is tried first. It could be that `zenity` is much more common because it's comes preinstalled with GNOME/Ubuntu...

**Comment by jlnrrg** [comment]
I debugged a little further and it does not seem to be an issue with the executable selection, but more with the `runExecutableWithArguments` function.

Basicly this is called, but nothing spawns and the return value is null.

```dart
runExecutableWithArguments(
      "/usr/bin/zenity",
      [
          "--file-selection"
          "--title",
          "File Picker",
      ]
    );
```

if I manually type `/usr/bin/zenity --file-selection --title "File Picker"` in my terminal, the file picker spawns no problem.

**Comment by philenius** [comment]
Thank you for investigating, @jlnrrg.

> First I though it is an access problem but with the following rights this seems unlikely:
> -rwxr-xr-x 1 root root 135960 Feb 27  2020 /usr/bin/zenity

I agree with you, this shouldn't be a problem as long as zenity has the e**x**ecutable-flag. On my computer, the zenity binary has the same permissions.

I would have one more idea: I always wondered how `Process.run()` handles arguments with blanks/whitespace. Are arguments with blanks automatically quoted? Maybe the segmentation fault is caused by the blank in the `title`. Could you retry with a single-word title so that `runExecutableWithArguments()` is invoked like this?
```dart
runExecutableWithArguments(
      "/usr/bin/zenity",
      [
          "--file-selection"
          "--title",
          "Dialog",
      ]
);
``` 
If a single-word title doesn't work either, could you please play around with `Process.run()`? `Process.run()` offers many more parameters which we currently do not use respectively never tried out:
https://github.com/miguelpruivo/flutter_file_picker/blob/32094fde2bcc21119712e14eeb078ad64bfdf1b0/lib/src/utils.dart#L49

**Comment by jlnrrg** [comment]
I decided to deinstall the qarma as it had the above mentioned permission issues and rather focus on the zenity issue as this comes preinstalled with ubuntu.
So after the deinstall I driggered this command: `await Process.run("/usr/bin/zenity", [file-selection","--title","Test"]);`, which again resulted in the `exitCode: -11` :disappointed: 

I will now play around with `Process.run()` and list my progress here:

- [x] `Process.runSync('zenit', ['--file-selection']);` -11
- [x] `Process.run('zenit', ['--file-selection']);` -11
- [x] `Process.run('yad', ['--file-selection']);` -11

**Comment by jlnrrg** [comment]
Good news first:
As it seems to be a permission issue, I tought about actually building the app and starting it (not using the debugger) and boom. **Everything works as intended.**

So the issue seems to lay in the flutter debugger not getting the same rights as to the real app.
I'll investigate this.

**Comment by jlnrrg** [comment]
The issue was most likely the usage of the snap vscode, bc when I installed the non-snap vscode everything worked as intended.
Thank you for your ongoing support :smile:.
With this my issue is resolved and I hope this will also help someone in the futute.

**Comment by philenius** [comment]
@jlnrrg thank you keeping us up to date on your investigations and for posting the solution :+1:

**Comment by samuelpismel** [comment]
I was having the same problem here. 
I lost some time to find this answer.
Would be nice to have this info in the wiki or readme.

Great lib btw 😄

Thanks guys
