### ISSUE TITLE
multiple files with same filename returns N times same File

### ISSUE THREAD

**Issue by renanyoy** [miguelpruivo/flutter_file_picker#938]
**Describe the bug**
if we pick multiple files with same filename one will crush the others
and we will get N times same file

**Platform**
- [X] Android

**Platform OS version**
Android 11

**Details to reproduce the issue**
pick multiples files with same filename in photo library
in my case I have lots of images named lomob.jpg in my photo library.

**log**
```
I/flutter ( 2960): |L2K|FileImage("/data/user/0/com.hbproptech.app.leads2keys/cache/file_picker/lo-mob.jpg", scale: 1.0)
I/flutter ( 2960): |L2K|post image CrQMaoLppygUqWJnCPPprQXG.jpg from /data/user/0/com.hbproptech.app.leads2keys/cache/file_picker/lo-mob.jpg
I/flutter ( 2960): |L2K|FileImage("/data/user/0/com.hbproptech.app.leads2keys/cache/file_picker/lo-mob.jpg", scale: 1.0)
I/flutter ( 2960): |L2K|post image ZHniNjivSHkfvxDUHrcfdpbV.jpg from /data/user/0/com.hbproptech.app.leads2keys/cache/file_picker/lo-mob.jpg
I/flutter ( 2960): |L2K|FileImage("/data/user/0/com.hbproptech.app.leads2keys/cache/file_picker/lo-mob.jpg", scale: 1.0)
I/flutter ( 2960): |L2K|post image zswpcvqAGUGnfRLWsDTnsoqg.jpg from /data/user/0/com.hbproptech.app.leads2keys/cache/file_picker/lo-mob.jpg
```

**Comment by miguelpruivo** [comment]
Does this happen on Android only?

**Comment by renanyoy** [comment]
I haven't tested but I think the fact that you don't use a random generated filename to share the file with the app must be a problem everywhere, even when picking files with same name from different folders..

**Comment by miguelpruivo** [comment]
@renanyoy I believe that the name is random

**Comment by miguelpruivo** [comment]
Can you please show me those original files URI's? It's odd that you can have multiple different files with the same name on the same location.

**Comment by wliu6v** [comment]
I hava the same problem.

What happens if I choose these two pictures below?

one is `/storage/emulated/0/Download/test.jpg`,
another one is `/storage/emulated/0/Pictures/test.jpg`

![image](https://user-images.githubusercontent.com/5987831/156119273-1ac0f778-b423-43a0-830d-503adb7ab629.png)


there's only one picture in `{app_package}/cache/file_picker/test.jpg`,which I think is wrong. I need both their original file names (both are test.jpg) and two different files in the cache directory.

![image](https://user-images.githubusercontent.com/5987831/156119627-91096953-8ea6-4aa5-980c-2b77b4146d18.png)


And even if it's the same file, and I select it at a different time, it may have different content (For example, if I modify my txt file and then upload it again). We can't use the one in the cache just because it has the same filename.

**Comment by wliu6v** [comment]
@miguelpruivo Would you like to take a look?

**Comment by renanyoy** [comment]
@miguelpruivo sorry hadn't seen your previous post.. I think the  file are all anonymized in the photo library, but it store the original name somewhere and give you that name in return..

**Comment by renanyoy** [comment]
on our doc servers we do the same, all files %random%.ext  and a file %randome%.description with a json containing mime, orinal name, etc..

**Comment by renanyoy** [comment]
it has been fixed ?
