### ISSUE TITLE
Do not pause app while showing picker on Android

### ISSUE THREAD

**Issue by jakobleck** [miguelpruivo/flutter_file_picker#949]
Closely related to https://github.com/miguelpruivo/flutter_file_picker/issues/813
Currently, on Anroid (working with Android 11, flutter 2.8.1 stable, file_picker ^4.3.0) the didChangeAppLifecycleState is called with state paused when a FilePicker is opened. Thus
1. one has to handle the Lifecycle in context with the FilePicker differently on Android vs iOS (the app remains active), (but, ok, not too bad,)
2. one has to stop background tasks after a certain time (a camera stream, for example, is killed after 60 seconds when the picker is shown),
3. (and worst, maybe) if the user opens the picker, then leaves the app while the picker is open (via home button or swiping up), this change in app activity can not be recognized because the app is already in state paused. One therefore has to assume that the app might have become paused (and been left for good) once the picker is opened.

Therefore, might be a good idea to change the behaviour of the FilePicker on Android systems similar to what happens on iOS after the abovementioned issue 813, i.e. showing the picker should not pause the app?

**Comment by Steve-flutter** [comment]
Is there any update on this issue?
I have an app that shows a Local Authentication (biometric) popup when the app goes to the background and then returns to the foreground. Currently, whenever the app enters the paused state and then the resumed state, the authentication popup is displayed.
However, when a file picker is opened within the app, it also triggers the paused and resumed lifecycle states, causing the biometric authentication popup to appear. Since the user is still interacting with the app through the file picker, the authentication should not be triggered in this scenario.
Is there a way to distinguish between the app being genuinely backgrounded and a file picker being opened from within the app?
