### ISSUE TITLE
The argument type 'Stream<List<int>>?' can't be assigned to the parameter type 'Stream<List<int>>'

### ISSUE THREAD

**Issue by bs90** [miguelpruivo/flutter_file_picker#952]
**Platform**

- [ ] Android
- [ ] iOS
- [x] Web
- [ ] Desktop

**Details to reproduce the issue**

I follow the guide on https://github.com/miguelpruivo/flutter_file_picker/wiki/FAQ (How do do I use withReadStream?) and got the error at this line.
```
var stream = http.ByteStream(file.readStream);
```
`http.ByteStream` extends `Stream<List<int>>` but `readStream` is `Stream<List<int>>?`
https://github.com/dart-lang/http/blob/c660daefa3d09505e4d3121f885b7ac41c732332/lib/src/byte_stream.dart#L10
https://github.com/miguelpruivo/flutter_file_picker/blob/master/lib/src/platform_file.dart#L57
I’m totally a beginner at Dart and Flutter. How can I fix that?
**Error Log**
The argument type 'Stream<List<int>>?' can't be assigned to the parameter type 'Stream<List<int>>'

**Flutter Version details**
Flutter version 2.8.1

**Comment by bs90** [comment]
`http.ByteStream(file.readStream as Stream<List<int>>);` fixed the problem.
Please let me know if there is a better way.

**Comment by philenius** [comment]
@bs90 you were very fast to close your issue :wink: Thank you, I updated the example in the FAQ.

Please do not use `http.ByteStream(file.readStream as Stream<List<int>>);`. This may cause a runtime exception because you're trying to convert `null` to a `Stream<List<int>>`.

Please read about sound null safety, a new feature of the Dart programming language, to understand why you got this error at first hand: https://dart.dev/null-safety

Long story short: the property `file.readStream` is nullable which means it can be null or it can contain an actual stream. So before you access the stream, you have to check first that is not null. I was confused in this case too, because usually I would check for null like this:
```dart
if (file.readStream != null) {
    // now do something with the stream because it can't be null
    http.ByteStream(file.readStream);
}
```
But the Dart compiler will still complain that `file.readStream` could be null. Unfortunately, the Dart compiler isn't intelligent enough to backtrack the non-null assertion on the nested variable `file.readStream`.

So you have to do a trick where you store `file.readStream` in a separate variable. Then, you can check that variable for null:
```dart
final readStream = file.readStream;
if (readStream != null) {
   // now do something with the stream because it can't be null
    http.ByteStream(readStream);
}
``` 
In this case, the Dart compiler understands that you checked for non-null and the code will compile. Of course the separate variable `fileStream` is unnecessary. You could also add an exclamation mark `!` after checking `file.readStream` for non null because you know that it cannot be null anymore. Using the `!` you can tell the Dart compiler that a value cannot be null (be careful with the `!` operator:

```dart
if (file.readStream != null) {
   // now do something with the stream because it can't be null
    http.ByteStream(file.readStream!);
}
```
