### ISSUE TITLE
on Android I can't get extension file audio

### ISSUE THREAD

**Issue by antonydieu** [miguelpruivo/flutter_file_picker#968]
Please help me when i choose audio file but can't get file extension
![Screenshot_20220217-223240_Files](https://user-images.githubusercontent.com/5988428/154515695-af3d2dec-982c-432a-83bd-98637de0d3b6.jpg)

**Comment by miguelpruivo** [comment]
@antonydieu the extension is retrieved from the file name, hence the reason why you probably can't get it, because the name doesn't have it.

**Comment by pvsvamsi** [comment]
@miguelpruivo I'm facing the same issue. On the device file manager, the file extension is shown. But the picker is not reading the extension.

**Comment by miguelpruivo** [comment]
Could you please send me one of those files and provide me with the environment details so I can try to replicate it? Thank you!

**Comment by pvsvamsi** [comment]
This issue is happening Vivo phone with Android 9. This is happening with all .mp3 files.
![WhatsApp Image 2022-02-21 at 10 59 23 PM](https://user-images.githubusercontent.com/20770470/155338686-583bdf4f-7869-4476-8dda-f76550c4e7f9.jpeg)
![WhatsApp Image 2022-02-21 at 11 37 42 PM](https://user-images.githubusercontent.com/20770470/155338695-f2d87ab3-8ec5-44a8-9dbd-a27b1faadb41.jpeg)

**Comment by miguelpruivo** [comment]
Device specific issues are harder to replicate/fix. I'm sorry. Specially those "not so famous brands" with OEM roms.

Sorry for any inconvenience. Let me know if you experience this issue in other brands as well.
