### ISSUE TITLE
How to use file_picker to delete a file?

### ISSUE THREAD

**Issue by kkazakov** [miguelpruivo/flutter_file_picker#974]
Because file_picker plugin actually makes a copy, I don't see a way to select which file to delete. Is that possible?

Or maybe the original uri should be exposed in the output result? Is there any elegant solution? I can't seem to find anything :(

**Comment by philenius** [comment]
@kkazakov you are probably looking for `clearTemporaryFiles()`, right? You can read about it in our Dart docs:
https://pub.dev/documentation/file_picker/latest/file_picker/FilePicker/clearTemporaryFiles.html

**Comment by kkazakov** [comment]
Actually, I want to delete the original file that's being selected. Not the copy created.

**Comment by philenius** [comment]
@kkazakov please also see: https://github.com/miguelpruivo/flutter_file_picker/issues/973#issuecomment-1047675667

**Comment by miguelpruivo** [comment]
@kkazakov like pointed out by @philenius, since SDK 30 you'll need to handle either a copy of the file (where you have the path) or use the `identifier` to actually manipulate the file natively — this is, the original resource. This plugin provides you with the `identifier` but you'll need to create a way to delete the native one.

A simple platform channel will fit your needs if you can't find any plugin for the purpose.

Sorry for any inconvenience.
