### ISSUE TITLE
`.glb` support

### ISSUE THREAD

**Issue by Tiny-Angel305** [miguelpruivo/flutter_file_picker#980]
I'd like this package filter to support the .glb file extension. It currently seems to support .gltf, but .glb is also one of major extensions for 3d models.

**Comment by miguelpruivo** [comment]
Hi, the package supports "all" the extensions, this means that it passes a filter with the extensions that you want to filter and it's up to the native platform to handled those, based on their MIME types.

If it doesn't support `glb` that's probably because it's a not supported MIME type (natively) and you'll have to set the filter to `FileType.any` and then discard the unwanted files (you can check the `extension` property) on your end.
